### ISSUE TITLE
Restage of Application

### ISSUE THREAD

**Issue by agracey** [epinio/ui#10]
A user should be able to restage or restart an application through the UI.

**Comment by jimmykarily** [comment]
The staging API endpoint [needs A BlobUID ](https://github.com/epinio/epinio/blob/main/pkg/api/core/v1/models/models.go#L141) to use when staging. The cli has that information from the previous call which uploads the code.

I understand this may not be possible in every flow, especially from the web UI. Maybe we can make that optional and use the last uploaded blob when the BlobUID is missing. Would that work for you?

Regarding "restart", we could either tweak the "Deploy" endpoint to not require a Stage or we can simply implement a new "Restart" endpoint.

**Comment by richard-cox** [comment]
@jimmykarily I missed this one from planning earlier, it has a dependency on https://github.com/epinio/epinio/issues/912 and you asked a question in your last comment that I'd defer to @agracey. I don't think it's a blocker for beta2 so have bumped out to 'later'

**Comment by richard-cox** [comment]
@jimmykarily Now that https://github.com/epinio/epinio/issues/912 has been completed, is https://github.com/epinio/ui/issues/10#issuecomment-946827905 now ready too or unblocked? If the later was there an epinio/epinio issue to track progress?

**Comment by jimmykarily** [comment]
@richard-cox there was no issue I think but since we have an org-level board now, I will simply add this story to the backlog.

**Comment by jimmykarily** [comment]
Created 2 stories:
- Restage endpoint: https://github.com/epinio/epinio/issues/1073
- Restart endpoint: https://github.com/epinio/epinio/issues/1074

**Comment by richard-cox** [comment]
I've now wired these two in and the feature will be included in the pending ui 0.3.3 release
