### ISSUE TITLE
App logs does not show up anymore when you create an app

### ISSUE THREAD

**Issue by juadk** [epinio/ui#100]
### Bug

When Cypress creates a new application, we can see the build log perfectly, however the app logs tab stays empty and we can see a failed websocket connection in the web dev console:

<img width="2096" alt="image" src="https://user-images.githubusercontent.com/6025636/165523544-2d8cfe6a-243f-4853-ae75-aa5f0f8c2d0a.png">

### Versions used

- epinio: `main branch` (https://github.com/epinio/epinio/commit/c097bd41117d15047d6f9e003f12ef8032875f2d)
- rancher latest: `2.6.4`
- ui-dashboard-index: `epinio-dev` (https://github.com/rancher/dashboard/commit/3961e89042602cae1d22d57771edcc0a3f2a2a82)

It I try to test it without Cypress, I can see the log appears even if there is still an error in the console:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/6025636/165525582-ec3435e3-290e-45e0-9173-4d06c8a4092c.png">

**Comment by jimmykarily** [comment]
We debugged this and we proved that, in the UI:

- when you start application logs after they they are initially printed, you still get them
- when you start application logs and new log lines appear, you get them too
- when the app logs tab is opened automatically (after building from the UI), the tab is empty even if there was an line printed. If the application keeps printing things, then all the lines appear (none is missing).


This sounds as if the logs are there but are not flushed for some reason, waiting for more output to appear. Or it's just a timing issue and we don't face it with every application. Then one we used is this:

https://gist.github.com/jimmykarily/1fc4046422f422e1530d03e797c5cb6a

**Comment by jimmykarily** [comment]
We increased the ticking interval to 30 seconds and had the first line printed immediately, updated the gist :

https://gist.github.com/jimmykarily/1fc4046422f422e1530d03e797c5cb6a

(in the old version, the "ticking" started after 2 seconds and every 2 seconds after that)

The new version reproduces the bug. No logs appear, not the first line and no line after that. There is also no apparent error in the console/network tabs.

**Comment by jimmykarily** [comment]
I tried again, first tick in 30 seconds and every 30 seconds after that. The logs appear in the app logs tab in the UI.

So to summarize, the bug only occurs when something is printed too fast when the application starts. I can interpret this yet. There are some errors in the epinio server logs but I'm not sure they are relevant. We have to disable polling and every other irrelevant request to be able to tell what's failing.

**Comment by richard-cox** [comment]
I've tweaked the UI to wait for the `deploy` request to complete before showing the log.

@jimmykarily Does the `/api/v1/namespaces/<ns>/applications/<app>/deploy` request wait for a specific app status before returning? If not, with the tweak we're all good

**Comment by jimmykarily** [comment]
@richard-cox [we call the helm client with `Wait: true`](https://github.com/epinio/epinio/blob/64e490e4dc1623326e0240abc2bef1a1afd525ab/internal/helm/helm.go#L182). So it waits until helm reports success. I think if you wait for the deploy request to succeed then you should be good.

**Comment by juadk** [comment]
It seems to be fixed with the latest `epinio-dev` branch, I will go further tomorrow.

**Comment by juadk** [comment]
Sometimes it passes and sometimes it fails...
When it fails, the tab with the log never appears and timeout is reached. I tried to increase the timeout but it still fails.
![image](https://user-images.githubusercontent.com/6025636/170253549-3aaec5ca-08c2-40ca-8c85-c8eecdd2334c.png)
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/2383509932
New bug? race condition? I don't know yet.

**Comment by juadk** [comment]
ok, after doing more tests, the bug is fixed.
Regarding my latest comment with the sporadic issue, I'm still checking what happens, I will open a different issue.
