### ISSUE TITLE
epinio UI names window tab in url as Rancher

### ISSUE THREAD

**Issue by claudioser** [epinio/ui#106]
**Describe the bug**
epinio UI names window tab in url as Rancher

Hint: Make sure to search through the existing issues, as they often contain important information on recent changes.

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Install epinio on k3s
2. Get the epinio url client for the epinio instance
3. login

**Expected behavior**
Window name tab should reflect something else than Rancher. see attached jpg
![epinio url](https://user-images.githubusercontent.com/53047113/168110594-3de5443a-a27c-4317-847e-f4438b99d159.jpg)

**Comment by richard-cox** [comment]
Fixed by https://github.com/epinio/ui-backend/commit/c9f9820a2f7c7da01a68e4dc7083752e3e6611b7. It'll need a rev of the standalone UI to fix, expected next week

**Comment by juadk** [comment]
### Fixed in latest UI version:
![image](https://user-images.githubusercontent.com/6025636/172999482-f008de0a-14a7-4507-8789-e60ab633e074.png)
