### ISSUE TITLE
Main content not displayed by default after upgrade to v.0.8.0

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrade to version 0.80, the UI only shows by default the navbar, not the content:
![image](https://user-images.githubusercontent.com/37271841/168617956-36980a51-3532-4906-8840-e6ff777f156e.png)

When clicking on the top left icon the left panel and the content are displayed, but the following error appears
`vue.runtime.esm.js:1897 TypeError: Cannot reading 'length'`

![image](https://user-images.githubusercontent.com/37271841/168618310-c6d56483-0518-4732-81b7-bd59486769cd.png)

### Expected Behavior

Page should load with left panel and application by default

### Steps To Reproduce

1.  Uninstall Epinio
2. Re-install Epinio on Rancher Desktop (https://docs.epinio.io/howtos/install_epinio_on_rancher_desktop)

### Environment

```markdown
- OS:MAC
- Architecture: Intel
- Epinio Version:0.80
- Cluster:
  - Provider: Rancher Desktop
  - Options:1 node
  - Kubernetes Version: 1.22.9
```

**Comment by jimmykarily** [comment]
Let's try this again after #1533

**Comment by mmartin24** [comment]
not observed in version v.9.0-0.0.3

**Comment by mmartin24** [comment]
not observed either when deployed v.0.9.0 with char version 0.11.0

![image](https://user-images.githubusercontent.com/37271841/174253579-936e8c4c-d469-426b-ab3b-a3fa4dfbe364.png)
