### ISSUE TITLE
[UI] UI should include UI upgraded version

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to version 0.80 the UI only displays 0.7.1 which seems to be the **epinio-ui** version
![image](https://user-images.githubusercontent.com/37271841/168623449-835b642f-eba7-4244-ac47-f56718422a25.png)

However it can be seen the **epinio-serve**r version is 0.80.0
![image](https://user-images.githubusercontent.com/37271841/168623341-37321106-e7ab-4cff-b8fa-5d7c7d7c9eaf.png)

### Expected Behavior

Epinio UI should reflect the Upgrade done

### Steps To Reproduce

1. Upgrade from version 0.7 to 0.80.0 with Rancher Desktop
2. Open the UI and observe the version at the bottom left
3. Observe it still displays "old" version rather than new one (that can be seen using in CLI: `kubectl get deployment -n epinio epinio-server -o yaml` )

### Environment

```markdown
- OS:MAC
- Architecture: Intel
- Epinio Version:0.80.0
- Cluster:
  - Provider: Rancher-Desktop
  - Options:1 node
  - Kubernetes Version: 1.22.9
```

**Comment by richard-cox** [comment]
This is a problem with the release process. The epinio ui version tracks the version of epinio (core) it's been verified on. At the moment there's a disconnect between when core Epinio releases and the UI does. In theory the Epinio chart shouldn't update until both core and UI are updated, but given the UI is slow to release I'm not sure that should happen.

Needs discussing with the team.

**Comment by richard-cox** [comment]
Going from the brief discussion in planning today, we'll go with the standalone UI showing the chart version (and not app version or UI version).

**Comment by juadk** [comment]
Validated in the latest release: :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/6025636/173601687-651ef51c-9b92-45bc-a169-2e8937e0f167.png)
@mmartin24 I think we can close it? do you agree?
Now we can see the version of the epinio helm chart 0.11.0

**Comment by jimmykarily** [comment]
We decided to show the epinio binary version: https://github.com/epinio/helm-charts/issues/230

**Comment by jimmykarily** [comment]
this is done
