### ISSUE TITLE
[UI] Add smallcaps validation for Namespaces prior creating them from Namespaces list

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#111]
**Is your feature request related to a problem? Please describe.**
Creating a Namespace with caps will trigger a 500 error once the "Create" button is clicked
Although the message is clear after this action is triggered, this could be prevented. 
![image](https://user-images.githubusercontent.com/37271841/168311202-8a512a59-6013-4f8e-aa4e-215d907e5ffb.png)

**Describe the solution you'd like**
Add a validation that informs the user about the problem with the name chosen and disable the "create" button until a correct name is provided as it currently happens with hyphen
![image](https://user-images.githubusercontent.com/37271841/168312552-3a2e99df-f02a-4ff9-bf2e-0fa501f3bcbe.png)

**Describe alternatives you've considered**
Add a tooltip or "i" icon explaining the rules for name creation

**Additional context**
This will improve the UX in early stages

**Comment by mmartin24** [comment]
Thanks @torchiaf .
I have checked the issue in latest `epinio-dev`, and it seems fixed. I could see:

- User prevented in advance if creating a namespace with caps with a nice and clear message
- `Create` button is disabled until this is corrected

![image](https://user-images.githubusercontent.com/37271841/227497822-a6551e04-caa4-421f-9cad-96e76f3d6adc.png)

I just have a question. At the time of writing this ticket, I believe the only place where to create a Namespace was precisely the `Namespaces` from the menu bar. However currently we can create namespaces also from Applications and Configurations, and there this implementation seems missing:

![image](https://user-images.githubusercontent.com/37271841/227498897-0ae592ad-e6f1-4814-815d-ea733d0e9a9d.png)

When attempting to create it correctly stops the user from doing so, but not in the graceful manner you implemented above.
![image](https://user-images.githubusercontent.com/37271841/227499126-2255c983-b0dd-4bf4-a1da-e5e35d915733.png)


Should we extend this behavior on this ticket or want me to create a new one?

**Comment by torchiaf** [comment]
Thanks @mmartin24 , I will check if the warning message can be easy applied to the `Configurations` tab and fix it in this PR. Otherwise I will open a separated issue; anyway I will update you here ASAP.

**Comment by mmartin24** [comment]
> Thanks @mmartin24 , I will check if the warning message can be easy applied to the `Configurations` tab and fix it in this PR. Otherwise I will open a separated issue; anyway I will update you here ASAP.

Thanks @torchiaf . Just as reminder, pls observe I  pasted the screenshot on the `configurations` tab but this occurs as well on the `applications` tab as commented above.

**Comment by richard-cox** [comment]
@torchiaf Is there an update for this?

**Comment by torchiaf** [comment]
> @torchiaf Is there an update for this?

I just created a new issue to handle the other namespace's validation separately: https://github.com/epinio/ui/issues/212
it's an easy fix but it requires some duplicated code, so I would prefer to do it after the validations library work. What do you think?

**Comment by richard-cox** [comment]
Lets get this one processed and closed to reflect the work in this milestone. I've updated the title to reflect this

**Comment by mmartin24** [comment]
ok. Retested again in `epinio-dev` scoped to `Namespaces` list solely.
![image](https://user-images.githubusercontent.com/37271841/231390599-95ba2e58-39ad-47bb-b5f6-3bdf75f2b81c.png)
