### ISSUE TITLE
[UI] Unable to create a configuration

### ISSUE THREAD

**Issue by juadk** [epinio/ui#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to create a configuration, the "Create" button stays grey and it never becomes clickable, even with an app bound.

<img width="914" alt="image" src="https://user-images.githubusercontent.com/6025636/170235979-0a4aff45-771d-4182-a1d6-35b5773c9289.png">

### Expected Behavior

The "Create" button should be clickable.

### Steps To Reproduce

1. Install k3s
2. Deploy Rancher with latest `epinio-dev` branch
3. Install Epinio
4. Compile and patch Epinio
5. Go to the UI and try to create a configuration

### Environment

```markdown
- OS: Linux
- Architecture: x86_64
- Epinio Version: main
- Cluster:
  - Provider: k3s
  - Options:
  - Kubernetes Version: 1.22
```

### Logs

```markdown
Nothing in the web dev console.
```

**Comment by richard-cox** [comment]
This is now fixed in `epinio-dev`
