### ISSUE TITLE
Feature Request: Include data-testid on UI elements for QA purposes

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#124]
### Is your feature request related to a problem?

It is sometimes complicated to locate things in the UI which are needed for the UI e2e tests.

### Solution you'd like

Having an specific locator for testing purposes such as `data-testid` would help significantly in key elements (forms, buttons, places where values are displayed...) would be tremendously valuable.

This is also valid to expose better values that are currently shown also as shadow elements only.

**Comment by richard-cox** [comment]
I've added documentation to a new 'best practise' guide in the developer documentation - https://github.com/epinio/ui/blob/dev/docs/developer/README.md#best-practises
