### ISSUE TITLE
[UI] - Using manifest file with a configuration should bind it by default

### ISSUE THREAD

**Issue by juadk** [epinio/ui#133]
When I was testing latest UI, I played with the manifest feature and something surprised me.
I have a manifest file which contains a configuration (conftest):
```
{"name":"manifesttest","configuration":{"instances":2,"configurations":["conftest"],"environment":{"tes1":"tee3","tret":"tert"},"routes":["manifesttest.172.18.0.2.omg.howdoi.website"],"appchart":"standard"},"origin":{"Kind":1,"git":{"repository":""},"path":"sample-app.tar.gz"}}%  
```
Then I created an app and import this manifest file, no configuration was bound by default:
![image](https://user-images.githubusercontent.com/6025636/173023953-02afa01c-b547-41b6-86d9-23edf79cf273.png)

If you want the configuration, you have to click on it:
![image](https://user-images.githubusercontent.com/6025636/173024132-9af9b5f4-e93f-43c4-9311-b11162ed9eb4.png)

I was expecting that the configuration would be automatically selected.

:warning: However, even if you do not select it, the configuration is bounded anyway, maybe just a display thing to fix/improve.

**Comment by mmartin24** [comment]
Checked on `epinio-dev and` working. 
Showing here differences before/after on this video:


https://user-images.githubusercontent.com/37271841/218967152-31891ecd-e59f-4a90-b54b-00487f20f40e.mov
