### ISSUE TITLE
[UI] - Bad redirection after deleting an app

### ISSUE THREAD

**Issue by juadk** [epinio/ui#134]
After deleting an app from its details page, if I click directly on the Create button:
![image](https://user-images.githubusercontent.com/6025636/173025956-9e2ebaab-b058-4243-9b20-b00edf3b897d.png)

I land on this wrong page:
![image](https://user-images.githubusercontent.com/6025636/173026136-f5013ec8-45d5-4355-9eb6-69c790c1d73d.png)

I was expecting to see the first screen with the different creation steps like source etc:
![image](https://user-images.githubusercontent.com/6025636/173026400-ceaf11af-7905-49de-a584-7d2bdc8faa8a.png)

It happens with latest epinio + epinio-ui `v0.9.0-0.0.3`

**Comment by mmartin24** [comment]
This seems ok to me. In attached video where I delete an app and click create button, the user is redirected to the `Source` step
[redirection_after_deletion.zip](https://github.com/epinio/ui/files/9350330/redirection_after_deletion.zip)

@juadk for me this one is ready to be closed, but I will leave it open a couple of days in case you want to check it by yourself.

**Comment by mmartin24** [comment]
If not mistaken this issue is already checked in this automated test: https://github.com/epinio/epinio-end-to-end-tests/issues/151 so should be detected if happens again.
I have updated our test plan with this issue.

**Comment by juadk** [comment]
> If not mistaken this issue is already checked in this automated test: [epinio/epinio-end-to-end-tests#151](https://github.com/epinio/epinio-end-to-end-tests/issues/151) so should be detected if happens again. I have updated our test plan with this issue.

Not sure about that, I have to check.

I think the issue can be closed.

**Comment by mmartin24** [comment]
> > If not mistaken this issue is already checked in this automated test: [epinio/epinio-end-to-end-tests#151](https://github.com/epinio/epinio-end-to-end-tests/issues/151) so should be detected if happens again. I have updated our test plan with this issue.
> 
> Not sure about that, I have to check.
> 
> I think the issue can be closed.

@juadk, here is where I was referring to: https://github.com/epinio/epinio-end-to-end-tests/pull/158/files
![image](https://user-images.githubusercontent.com/37271841/185388621-24f97bcd-5b59-410f-8819-1c0c8e3a5127.png)

**Comment by juadk** [comment]
That's not the same situation, in the code you linked, there is an extra step between `deleteApp` and `createApp` ==> `deleteConfiguration`. So it does not click on the Create button right after the app deletion.

**Comment by mmartin24** [comment]
> That's not the same situation, in the code you linked, there is an extra step between `deleteApp` and `createApp` ==> `deleteConfiguration`. So it does not click on the Create button right after the app deletion.

Old link. I looked at VSCode with the latest, but pasted the initial test without the current version.
That was the initial test and included a `deleteConfiguration` in the middle.
This is the current test in place and that middle part is not present: https://github.com/epinio/epinio-end-to-end-tests/blob/main/cypress/support/tests.ts  so it goes directly from `deleteApp` to `createApp`
![image](https://user-images.githubusercontent.com/37271841/185419648-e0089429-27e4-41ed-8e18-0e49deeb1251.png)
However, even when it does go straight from deleting to creating it seems still may not be ok. I just checked the content of `createApp` and it clicks first on to the Applications menu first:
```
Cypress.Commands.add('createApp', ({appName, archiveName, sourceType, customPaketoImage, customApplicationChart, route, addVar, instanceNum=1, configurationName, shouldBeDisabled, manifestName, serviceName, catalogType}) => {
  var envFile = 'read_from_file.env';  // File to use for the "Read from File" test

  cy.clickEpinioMenu('Applications');
  cy.clickButton('Create');
```
So even when the functions go straight from deletion to creation the steps are not the same.
It needs to be covered as well  this scenario
