### ISSUE TITLE
[UI] Feature Request: Close app logs and exec windows when underlying app or parent namespace is deleted

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#135]
### Is your feature request related to a problem?

Currently, on version 9.0-0.0.3 if I click on clear button and I delete the namespace the logs are cleaned, but the parent windows stay. This may result misleading for the user
![image](https://user-images.githubusercontent.com/37271841/173346854-0e0e271b-ec69-4f0f-af95-8cab9b04173a.png)

### Solution you'd like

Close the windows tabs that contained old logs already cleared.

**Comment by richard-cox** [comment]
@scures We still need to agree a flow for validating issues with Julien / Manuel. I've previously kept them open and moved them to `To Test` - https://github.com/epinio/ui/projects/1 for when a UI release is made (will do the same with this one). @juadk / @mmartin24 Shall we continue with that pattern?

**Comment by mmartin24** [comment]
https://github.com/epinio/ui/issues/135#issuecomment-1215273309

Thanks @scures and @richard-cox for the heads up.  I am normally ok with keeping things as they were, unless I am quite sure about a change, bu  I am not sure exactly how the process went and for which tasks this was followed; for instance do all UI tasks or just the one reported by us?, did we normally do a previous checkup with latest dev version?, when you say a UI release is made, do you mean directly pushed into epinio or ready to be pushed? Maybe we can clarified them separately.

**Comment by mmartin24** [comment]
I just checked this issue on latest dev with latest UI and unless I am missing something I am not sure I am seeing the change:

![image](https://user-images.githubusercontent.com/37271841/184812177-0fc87107-abd6-4a21-bef1-5367f369c693.png)
Am I missing something perhaps

**Comment by richard-cox** [comment]
@mmartin24 I'm not sure we officially had a process, but would be good to have one agreed by all now. It would be good to have QA test all new feature and bug issues (some issues will be more framework orientated that won't need validating). 

From our side the validation could be done in either a dev build (building the UI locally from epinio-dev) or from a UI release (the UI is built and bundled with Epinio, so tests are done from the UI deployed in epinio). The former would be quicker and wouldn't be blocked waiting for a new build, the latter a more fitting environment to validate in though. That decision one is up to you.

**Comment by mmartin24** [comment]
Just retried with newest version and see it there. Probably the pr is still not in. @scures, would you pls ping me when it is in?
Thank you.

**Comment by juadk** [comment]
> @richard-cox, sorry, I then misunderstood you when you said above ([#135 (comment)](https://github.com/epinio/ui/issues/135#issuecomment-1215273309)) if we should continue the pattern; I thought there was a process in place. If it was not and the aim is to have one, I think it should start by testing in dev, since testing right before release as first time can be very time-consuming and delay things. Ideally, it would be both, when the task is still in dev and after releasing but always that a person can keep up with everything. I'd like to share this thought with the QA team as well before saying something definitive.

@mmartin24 I agree with you.

**Comment by mmartin24** [comment]
Tested on epinio version `v1.1.0-68-g9f88f884` and working. 
Deleting the workspace or the individual apps before clearing or with or without clearing the logs will now close the tabs.


![image](https://user-images.githubusercontent.com/37271841/188420572-745d9ae0-becb-480e-b544-a4a53678f341.png)
![image](https://user-images.githubusercontent.com/37271841/188420645-8ec59900-660e-4b71-b287-57a45065a902.png)
