### ISSUE TITLE
[UI] - Broken dashboard with rc1

### ISSUE THREAD

**Issue by juadk** [epinio/ui#138]
After installing a fresh epinio 1.0.0-rc1, I got this homepage in the dashboard:
![image](https://user-images.githubusercontent.com/6025636/174308014-b7bb1a72-5310-4d99-9481-d7777591ac70.png)

Step to reproduce:
- Create k3d cluster
- Deploy epinio with: 
`helm install --devel epinio -n epinio --create-namespace epinio/epinio --set global.domain=${DOMAIN}`

I believe I saw it yesterday when I forgot to use EXCLUDES_PKG=rancher-components variable before building my local dev env.

**Comment by richard-cox** [comment]
The next build (containing https://github.com/epinio/ui/issues/138) should resolve it

**Comment by richard-cox** [comment]
Depends on https://github.com/epinio/helm-charts/pull/235, but i've tested with below and get the expected result

```
kubectl set image -n epinio deployment/epinio-ui epinio-ui=ghcr.io/epinio/epinio-ui:v1.0.0-0.0.4
```

**Comment by juadk** [comment]
Sorry, I forgot to update this one.
Tested successfully with epinio-ui:v1.0.0-0.0.4 and all good in rc2 😄

**Comment by juadk** [comment]
Sorry, I forgot to update this one.
Tested successfully with epinio-ui:v1.0.0-0.0.4 and all good in rc2 😄
