### ISSUE TITLE
Users should only be allowed to specify archive files when source type is archive

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An user can upload a single Python file in the process of creating an application.

![image](https://user-images.githubusercontent.com/37271841/175516650-90fa7343-6326-4169-9cb3-5663814e1953.png)

### Expected Behavior

Users should not be able to upload single python files

### Steps To Reproduce

Install Epinio releae 1.0.0
Create an application
Upload the single file within here: [simple_python.zip](https://github.com/epinio/ui/files/8975415/simple_python.zip)
Observe how user is not prevented

### Environment

```markdown
- OS:Linux
- Architecture:
- Epinio Version: 1.0.0
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by jimmykarily** [comment]
Neither the front-end nor the back-end should allow this. We support only a number of archive types and those are the only files that should be allowed. Staging shouldn't continue when the uploaded file is not a supported type.

**Comment by jimmykarily** [comment]
These are the archives we support: https://github.com/epinio/helm-charts/blob/3954c214de3d7b957cfc2054ba4fa4bfa140f5a3/chart/epinio/templates/stage-scripts.yaml#L27-L62

**Comment by jimmykarily** [comment]
Started working on the backend validation on this branch: [ui143-validate-archive-type](https://github.com/epinio/epinio/tree/ui143-validate-archive-type)

**Comment by jimmykarily** [comment]
I'm keeping this open until the front end validation is also implemented

**Comment by jimmykarily** [comment]
[This is the tracking issue for the frontend](https://github.com/rancher/dashboard/pull/6538). We can close this one.
