### ISSUE TITLE
Use the epinio server version from api rather than helm chart/env var

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#145]
- Following on from https://github.com/epinio/epinio/issues/1581, rather than use a helm chart value we should get the version from the api info call
- Need to consider whether we remove the plumbing of the helm chart (epinio ui backend env var, helm chart entry, CI to update helm chart value, etc)

**Comment by mmartin24** [comment]
@scures, I think I am still seeing the same in `epinio-dev`?
![image](https://user-images.githubusercontent.com/37271841/219035684-cabaa3d9-754b-470d-b0fb-13510f6f656b.png)

**Comment by thehejik** [comment]
@scures thanks but still see the same issue as Manuel. I'm using a custom epinio binary and latest `ghcr.io/epinio/epinio-ui:latest-next` image where the fix should be present.

**Comment by richard-cox** [comment]
@scures We should be able to strip the number and github commit to fetch a valid version
