### ISSUE TITLE
[UI] Missing Icons Service Catalogs 

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the UI Icons on catalog's menu are missing icons.

![image](https://user-images.githubusercontent.com/37271841/179469464-51a27389-faf4-4d43-9bf2-ce4bda1af7d2.png)

### Expected Behavior

A different icon on any Catalog service should be displayed.

### Steps To Reproduce

- Deploy latest epinio using k3d:

```
make acceptance-cluster-setup 
export KUBECONFIG=$PWD/tmp/acceptance-kubeconfig 
make install-cert-manager 
make prepare_environment_k3d 
```

- Go to Catalogs on the side menu

### Environment

```markdown
- OS: Linux
- Architecture: 
- Epinio Version: 
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by richard-cox** [comment]
We're reaching out to bitnami and fetching whatever icons they serve us for their charts. As Sorin says these were updated to generic icons related to chart type. 

![image](https://user-images.githubusercontent.com/18697775/183705086-12ed3cf8-a99c-46b0-a5e8-0ba1e76f0835.png)

Given their change, i don't think we should do anything custom and this can be closed

**Comment by mmartin24** [comment]
I am sorry, I did not see the new icons appearing on the latest dev.
Not sure if I missed anything.

**Comment by richard-cox** [comment]
We show the icons supplied by bitnami, they've changed them to those shown in the issue description. I don't think we should overwrite these, so there's no new icons. So I think this can be just closed

**Comment by mmartin24** [comment]
ok, if the icons are not there and we cannot use others then let's close it. We know the reasons, so it is a known issue.
