### ISSUE TITLE
[UI] Show additional deployment information for apps deployed via Github

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#150]
- Covers step 2 & 3 from https://github.com/epinio/ui/issues/63#issuecomment-1164180440
- Persist the information used when creating an app from github.
- Use the information to show additional detail in the app detail page
- User should be able to view commits from the branch and select one to deploy from
  - This will probably mean using the app progress component in a new page

**Comment by richard-cox** [comment]
@scures Not sure where we got to on this one, is https://github.com/rancher/dashboard/pull/6852 ready to review (after conflicts updated)?

**Comment by richard-cox** [comment]
https://github.com/epinio/ui/issues/171

**Comment by mmartin24** [comment]
Checked:
To test I used this repo with 5 commits: https://github.com/epinio/example-go/commits/main and deployed the latest
Once the app is deployed I checked the following:

- Additional details is shown in detail page so  information is persisted and works as displayed here:
![image](https://user-images.githubusercontent.com/37271841/219031533-2da5e8c0-6129-4e15-9ab3-073d3799b74b.png)

- Deployed commit from which app is running is displayed. When I click on `Revision` I am taken to the code in Github of the specific commit where I deployed from.
![image](https://user-images.githubusercontent.com/37271841/219033200-866843b4-cb0b-439e-9008-cd53c8d0f686.png)

@richard-cox , I am not sure how to check this:
>User should be able to view commits from the branch and select one to deploy from
This will probably mean using the app progress component in a new page

I am seeing only 1 commit, but there are several in this example (https://github.com/epinio/example-go/commits/main) . Am I perhaps missunderstanding what should happen here?

**Comment by mmartin24** [comment]
ok, thank you @scures for the clarification.
I can see indeed the commits on the new tab on the left just the selection is not ready at this point. Ok noted that for further release. Closing ticket with that in mind.
![image](https://user-images.githubusercontent.com/37271841/219295230-f1b3404b-ce36-4862-b6cb-d783b88c1fcb.png)
