### ISSUE TITLE
[UI] Removing namespace modal won't focus the input field.

### ISSUE THREAD

**Issue by scures** [epinio/ui#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While removing a namespace, the input for the `namespace name` won't focus.
![missing](https://user-images.githubusercontent.com/88777903/185078294-69eef482-ea04-4cd3-8201-d800c8275105.gif)

### Expected Behavior

Opening the remove modal should focus on the input field.on 

### Steps To Reproduce

- Go to `Namespaces`
- Click on the actions button (far left on the table element)
- Click remove
- Input will not be focus, if you start typing directly it won't capture it.

**Comment by richard-cox** [comment]
This may be something we do in the core dashboard promptRemove

**Comment by mmartin24** [comment]
Tested on branch with epinio version `v1.2.0-38-gf9ab365e` and working:

https://user-images.githubusercontent.com/37271841/192810063-cb1e5f56-68a9-4b3a-ba95-46eeebfdc5ba.mov

**Comment by mmartin24** [comment]
Checked in `(epinio-dev)` with `Epinio Server Version: v1.4.0-2-gf74b18dc` and working
