### ISSUE TITLE
Error parsing a stringify JSON, deployment

### ISSUE THREAD

**Issue by scures** [epinio/ui#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While trying to deploy an application and we're setting an `env` variable with a stringify object, the backend will return an error:
```
Server Backtrace: error converting YAML to JSON: yaml: line 3: did not find expected ',' or '}'
```

Request payload:
![image](https://user-images.githubusercontent.com/88777903/185891513-78272439-e32b-4994-8f5f-76d6047d74f6.png)

Tested in CLI with an example where it will work and fail:
![image](https://user-images.githubusercontent.com/88777903/185892081-a8fc03d9-36f3-43c1-b247-161bbd8e40ae.png)

### Expected Behavior

Should correctly parse the object.

### Steps To Reproduce

1. Have an application deployed
2. try to add a new env variable to it
```
epinio apps env set {{YOUR_APP}} foo "{\"usernameOrOrg\":"scures","url":"https://github.com/scures/epinio-sample-app","commit":"3ce7abe14abd849b374eb68729de8c71e9f3a927"}"
```

A server error will occur, the new variable will be set anyway with the correct format.

**Comment by andreas-kupries** [comment]
Does it also happen if the application only exists and is not deployed ? I.e. for

```
epinio apps create {{YOUR_APP}}
epinio apps env set {{YOUR_APP}} foo "{\"usernameOrOrg\":"scures","url":"https://github.com/scures/epinio-sample-app","commit":"3ce7abe14abd849b374eb68729de8c71e9f3a927"}"
```

**Comment by andreas-kupries** [comment]
Ok, that seems to point to the deployment code to have an issue, not the basic storage of the data in the kube resources ...
Ah! It is very likely that the generation of the `values.yaml` for the helm chart used to deploy the app goes wrong and then helm chokes on it. values.yaml - Have to have a look, I do not believe that this is properly marshalled, i.e. with json as string it is extremely likely to improperly quoted, i.e. not at all.

**Comment by andreas-kupries** [comment]
Can you transfer this issue over to the `epinio` repository ? As it fails for CLI, and server side this is not really an UI issue.

**Comment by andreas-kupries** [comment]
Relevant parts of the code

- https://github.com/epinio/epinio/blob/main/internal/helm/helm.go#L144-L168
- https://github.com/epinio/epinio/blob/main/internal/helm/helm.go#L94-L99
- https://github.com/epinio/epinio/blob/main/pkg/api/core/v1/models/env.go#L60-L68

**Comment by andreas-kupries** [comment]
Thanks. Although the `Transfer Issue` button/link on this page would have been more convenient. And reminds me that I could have done this myself. Apologies for having you doing it.
