### ISSUE TITLE
Default builder image from installation not respected

### ISSUE THREAD

**Issue by jimmykarily** [epinio/ui#154]
Blocks epinio/epinio#1248 

- Deploy epinio and set the default builder image to something different that [the default `full` tag](https://github.com/epinio/helm-charts/blob/8ae23b5973bfc08444ea0e8769c281a294894691/chart/epinio/values.yaml#L23)
- Push an application from the web UI
- The the image used in the staging Pod

It should have been the custom tag but it's just `full`. Checking the App custom resource shows that the `full` builder image was set by something:

```
kubectl  get apps.application.epinio.io -n sample sample -o yaml
...
  builderimage: paketobuildpacks/builder:full
...
```

I get this on an airgapped rancher environment with many other modifications (as part of [this](https://github.com/epinio/epinio/issues/1248)) so we need to reproduce this on a regular setup.

**Comment by mmartin24** [comment]
Just tested this issue the same way as in [here](https://github.com/rancher/dashboard/pull/6756#issuecomment-1228344749) with latest version of and seemed to work:

```
✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.20.11+k3s2
Epinio Server Version: v1.1.0-68-g9f88f884
Epinio Client Version: v1.1.0-68-g9f88f884

Done preparing k3d environment!
                                                
➜  epinio git:(main) ✗ kubectl  get apps.application.epinio.io -n workspace go-app-tiny -o yaml
apiVersion: application.epinio.io/v1
kind: App
metadata:
  annotations:
    epinio.io/created-by: admin
  creationTimestamp: "2022-09-05T09:15:44Z"
  generation: 4
  name: go-app-tiny
  namespace: workspace
  resourceVersion: "9912"
  uid: 45b34755-d36b-48e3-8823-b49eccb8a7c6
spec:
  blobuid: 016e0bd1-3f9c-4f10-a7ae-039b75d46616
  builderimage: paketobuildpacks/builder:tiny
  chartname: standard
  imageurl: registry.epinio.svc.cluster.local:5000/apps/workspace-go-app-tiny:470d0bdad5c538c9
  origin:
    git:
      repository: https://github.com/epinio/example-go
      revision: main
  routes:
  - go-app-tiny-a279f.172.19.0.3.omg.howdoi.website
  stageid: 470d0bdad5c538c9

```

![image](https://user-images.githubusercontent.com/37271841/188417051-9ed29ff0-55ef-46cd-a2ec-ef97a267b0ba.png)
