### ISSUE TITLE
[UI] Cannot bind Service to App via the Service 

### ISSUE THREAD

**Issue by enrichman** [epinio/ui#155]
**Describe the bug**
It's not possible to select an application and bind it to a service from the service configuration.  

The _Save_ button is **disabled**.

![image](https://user-images.githubusercontent.com/1763949/189317371-e6d2e89d-ff8d-419c-bae6-860cf54ea2a6.png)

**To Reproduce**
Create a service.
Create an app (do not bind it to the service yet).
Go to the service page and edit the configuration.
Select the app to bind.
The _Save_ button is disabled.

**Expected behavior**
It should be possible to save a modified configuration.

**Comment by mmartin24** [comment]
Tested on `epinio-dev` with `Epinio Server Version: v1.4.0-2-gf74b18dc` and working.
Checked binding and unbinding after test creation from service page
![2022-10-24_13-45](https://user-images.githubusercontent.com/37271841/197520001-dfd252de-1d24-4fe1-af8e-997960b72c9d.png)
![2022-10-24_13-46](https://user-images.githubusercontent.com/37271841/197519996-c0910ad3-1c52-4010-83ae-1b9c636c9b57.png)
