### ISSUE TITLE
[UI] For an application, all the Services are shown as bound 

### ISSUE THREAD

**Issue by enrichman** [epinio/ui#156]
**Describe the bug**
If multiple services are available then all of them are shown as bound, while only one (or part of them) is bound instead.

### Application
![Screenshot from 2022-09-09 11-34-16](https://user-images.githubusercontent.com/1763949/189321085-7b901028-0b38-4261-8cad-b35078cbd3d7.png)

### Application > app detail
![Screenshot from 2022-09-09 11-36-08](https://user-images.githubusercontent.com/1763949/189321095-7971e957-de95-4f7c-ab0c-fd75843cc362.png)

### Application > app detail > config
![Screenshot from 2022-09-09 11-37-22](https://user-images.githubusercontent.com/1763949/189321104-813bdeea-b2c6-4c44-9d19-7bff6023d2df.png)

You can see from the Services page only one service was bound instead (you can also check this from the configuration).

![Screenshot from 2022-09-09 11-38-51](https://user-images.githubusercontent.com/1763949/189321540-7810ec12-dbcd-4b35-b71a-24c86c3c0391.png)

**To Reproduce**
Create multiple services.
Create an app and bind it only to a service.

**Comment by mmartin24** [comment]
Checked on `epinio-dev` branch with `Epinio Server Version: v1.4.0-2-gf74b18dc` and working

![image](https://user-images.githubusercontent.com/37271841/197570370-c5533baf-eff1-4c59-a363-e6a04fdf36da.png)
![image](https://user-images.githubusercontent.com/37271841/197570497-ac474883-f2c1-4999-ae6c-a3cc68f2e5a1.png)
