### ISSUE TITLE
Create Epinio Icons

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#16]
There's two locations we show an epinio icon

- Sidebar nav. As per other global apps
  - ![image](https://user-images.githubusercontent.com/18697775/137307479-b3b987d3-bb9d-4e88-9578-ff291bb53f98.png)
- Header when naved to a specific cluster
  - This matches how harvester shows an image
  - At the moment the image is from the epinio website and warped to a specific size
  - If this is fine i'll shrink it down properly
  - ![image](https://user-images.githubusercontent.com/18697775/137307684-2af83e46-d724-43df-be88-c5c605828dcb.png)

**Comment by richard-cox** [comment]
@agracey Are there any special requirements from you before Lauren takes a look?

@lvuch Let me know if you'd like too see these locations in action

**Comment by lvuch** [comment]
Icon added to set via dashboard
