### ISSUE TITLE
Test namespaces filter

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#163]
Test several scenarios of the namespaces filters and clarify behavior including:

- Check filters apply to Applications
- Check filter apply to Configurations
- Selection / deselection of items
- Chips are added into box

**Comment by mmartin24** [comment]
I checked the filter after creating 3 namespaces, 3 applications binded to each namespaces and several configurations.
When I apply the filter it simply hides all results, but does not filter

Check the following video


https://user-images.githubusercontent.com/37271841/191272166-cf89c834-1314-40cb-a1de-6586594e8558.mov


@richard-cox , can you confirm this is a bug?

Also, could you please confirm the namespace filter behavior. I mean, should it filter namespaces, configurations and applications binded to an specific namespace?

**Comment by richard-cox** [comment]
The namespace filter applies to namespaced resources, so won't affect the `namespace` list. The other two though should only show resources associated with the selected namespace in the filter, so it looks like there's a bug there

**Comment by mmartin24** [comment]
Ok, thanks for confirming. Reported bug here: https://github.com/epinio/ui/issues/164
Closing issue
