### ISSUE TITLE
[UI] Namespaces top header filter not filtering applications and configurations

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue:
Top header filter for namespaces fail to filter apps and configurations. It hides them instead.

Example:

https://user-images.githubusercontent.com/37271841/191685581-d621f13f-3d2f-4489-906b-ff9db1397d3a.mov

### Expected Behavior

Filter should be applied and display the apps / configuration associated to that namespace filtered.

### Steps:
- Create several namespaces
- Create several apps and configurations associated to each namespace created
- Filter by namespaces on Application or Configuration menu

### Environment

```markdown
- OS: Linux
- Architecture: amd64
- Epinio Version: v1.2.0-23-g11a2d241
- Cluster:
  - Provider:k3d
  - Options:
  - Kubernetes Version:v1.20.11+k3s2
```

**Comment by richard-cox** [comment]
We should re-test this after merging in `rancher/master`

**Comment by mmartin24** [comment]
Tested on `epinio-dev` and working:

https://user-images.githubusercontent.com/37271841/198076199-328d8a96-4d4d-4792-b1b6-c1c2b7da3ef9.mov
