### ISSUE TITLE
Feature Request: Display default Epinio binary links for macOS and Linux not arm ones

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#166]
### Is your feature request related to a problem?

**Issue**:
Binary links displayed on Epinio for macOS and Linux point to `arm64` which perhaps is not the most common ones
![image](https://user-images.githubusercontent.com/37271841/194228298-4f2c8f44-cb0c-4377-8106-8278f88d2515.png)

### Solution you'd like

Perhaps they could be pointed out to most common ones like:

epinio-darwin-x86_64
epinio-linux-x86_64

**Comment by mmartin24** [comment]
thanks @scures; we should probably ask the rest of the team what they think.
My initial thought would be to be consistent, so if we do something special for Mac, I guess we should also do it for Linux.
Just one question in this matter, would it be easier just to list in for each specific OS all the possibilities in its specific row?

**Comment by richard-cox** [comment]
We're limited to the downloads provided by the release (for example https://github.com/epinio/epinio/releases/tag/v1.4.0). We could do something to try and work out the processor type given the browser string (if it's there), but I think for now showing the most common one's with a link where the user can see more is fine (which will be the case once we get #7261 merged)

**Comment by mmartin24** [comment]
> I would say go with this for now and we can revisit it (if needed) in the future. What do you think @mmartin24 ?
thanks @scures. Let's take it  in epinio standup and we decide there.

**Comment by thehejik** [comment]
This is resolved in `epinio-ui:v1.5.1-0.0.3`:
![image](https://user-images.githubusercontent.com/12828077/204854203-ffb915df-adee-40f5-b613-e443092241d0.png)
