### ISSUE TITLE
[UI] Implement batch deletion APIs

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#168]
This is a global issue to implement the new batch deletion APIs. Epic https://github.com/epinio/epinio/issues/1739
- Application - https://github.com/epinio/epinio/issues/1742
- Configuration - https://github.com/epinio/epinio/issues/1740
- Services - https://github.com/epinio/epinio/issues/1743

Usually when the prompt remove modal deletes multiple resources we choose whether to do them sequentially or in parallel. Here we need to override that process and call the new APIs. I think there's a mechanism for this already

**Comment by mmartin24** [comment]
Tested and working. Checked the follwing requests on `epinio-dev`

## Configurations
Bulk deletion of 2 configurations: `configuration1` and `configuration2` on 1 request
```
https://epinio.192.168.16.3.omg.howdoi.website/pp/v1/direct/r/ZThhPrryoUeUuimbk4Gb-G3-I9A/api/v1/namespaces/workspace/configurations?configurations[]=configuration1&configurations[]=configuration2
```

## Services
Bulk deletion of 2 services: `svc1-mysql` and `svc2-rabbit` on 1 request
```
Request URL: https://epinio.192.168.16.3.omg.howdoi.website/pp/v1/direct/r/ZThhPrryoUeUuimbk4Gb-G3-I9A/api/v1/namespaces/workspace/services?services[]=svc1-mysql&services[]=svc2-rabbit
```

## Applications
Bulk deletion of 2 services: `app1` and `app2` on 1 request
```
Request URL: https://epinio.192.168.16.3.omg.howdoi.website/pp/v1/direct/r/ZThhPrryoUeUuimbk4Gb-G3-I9A/api/v1/namespaces/workspace/applications?applications[]=app1&applications[]=app2
```

Checked as well that bulk deletion of apps bound to configurations and services worked as well. Noticed `unbind
: true` on requested payload.

Comparison between both for applications:
Before (sequential)
![bulk_deletion_before](https://user-images.githubusercontent.com/37271841/219027525-9d3653e7-8973-401f-839e-548c78e02c59.png) 

Now:
![bulk_deletion_apps](https://user-images.githubusercontent.com/37271841/219027568-ce060942-d0af-4cc5-90bc-d16d230032c6.png)
