### ISSUE TITLE
Routes not displayed in UI on new deployed apps

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#169]
### Issue:

Routes are not displayed in UI when an app is pushed

![Image](https://user-images.githubusercontent.com/37271841/197984827-79667877-399d-4cd8-9db1-1d4294be69a2.png)

Possibly related to: https://github.com/epinio/epinio/issues/1799

Checked on `Epinio Server Version: v1.4.0-18-g12e7d143` using UI `v1.2.0.0.0.1`

Note: custom routes created after initial deployment are displayed:

![Image](https://user-images.githubusercontent.com/37271841/197985880-3456b960-c431-4e43-8159-b8180ef57e4a.png)

**Comment by andreas-kupries** [comment]
> That's correct @andreas-kupries , it's using `[]` to ask for default. So changing it to ask for `null` will pretty much solve this, right?

Yes

**Comment by richard-cox** [comment]
The code has been merged to `epinio-dev`. @mmartin24 I think it's probably time to change back the UI source used in the CI pipeline from the tag to `epinio-dev`. Note - The CI will need to run the UI with the new env vars just like when you run the UI locally

**Comment by mmartin24** [comment]
Thanks @richard-cox . We will switch back the ci to `epinio-dev` and will check how it goes

**Comment by mmartin24** [comment]
Tested fixed locally on local `epinio-dev` and working:
![image](https://user-images.githubusercontent.com/37271841/198037013-7610ab92-e9c5-41d8-8704-e399c84821f7.png)

**Comment by mmartin24** [comment]
> The code has been merged to `epinio-dev`. @mmartin24 I think it's probably time to change back the UI source used in the CI pipeline from the tag to `epinio-dev`. Note - The CI will need to run the UI with the new env vars just like when you run the UI locally

@richard-cox , the changes have been applied to latest epinio qa image and works. Thanks

**Comment by mmartin24** [comment]
Closing issue.
