### ISSUE TITLE
[UI] Add ability to update an Application's Source

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#171]
- Currently user can only update minor parts of an existing application
- User's should also be able to supply new source for it

**Comment by richard-cox** [comment]
We should be able to show the same component as the wizard. There's a UX issue though in how we show the progress of the multiple https requests to support changing the source (supply source, apply source, restart, etc). In the wizard we have a full step for it, but when editing the app we don't

**Comment by mmartin24** [comment]
@richard-cox Yesterday and today I checked on `epinio-dev` and I am not sure if this is working or I am doing something wrong but when I try to update a source I simply can't and get several errors:

![image](https://user-images.githubusercontent.com/37271841/231971065-21921344-9467-46df-b620-45dc4acc54ad.png)

Is it a bug?

**Comment by torchiaf** [comment]
> @richard-cox Yesterday and today I checked on `epinio-dev` and I am not sure if this is working or I am doing something wrong but when I try to update a source I simply can't and get several errors:
> 
> ![image](https://user-images.githubusercontent.com/37271841/231971065-21921344-9467-46df-b620-45dc4acc54ad.png)
> 
> Is it a bug?

@mmartin24  I can take a look.

**Comment by mmartin24** [comment]
Opened a bug for the previous one for better tracking: https://github.com/epinio/ui/issues/217. Not sure if this one is also related: https://github.com/epinio/ui/issues/218

**Comment by mmartin24** [comment]
Quick question regarding env vars update.
I remember @richard-cox told me at the moment you need 2 steps to if you wanted to add an env var (1 for saving it and 1 for updating) but I was surprised you only need 1 to remove the env vars and get the app in a non-working state
Is this expected?

**Comment by richard-cox** [comment]
There should only be one step to update env vars (and custom values), however they won't apply to an existing app until the app is restarted.

**Comment by mmartin24** [comment]
> There should only be one step to update env vars (and custom values), however they won't apply to an existing app until the app is restarted.

But why it seems to apply when removing the env vars in one step?

**Comment by mmartin24** [comment]
Tested this in latest epinio-dev and seem to work fine.
It seems to work, I tried updating from different sources including:

Image -> file app
File -> Folder
Folder -> File
Github -> Gitlab
Gitlab -> Github
Github commit 1 -> commit 2
Gitlab commit 1 -> commit 2

![image](https://user-images.githubusercontent.com/37271841/232706678-45505c29-e439-4183-bb46-a7de37cf756b.png)


### Corner cases:
- https://github.com/epinio/ui/issues/216 (already being fixed)
- Application stops working in the moment that env vars are removed (without restart) but not the other way around.  Is it expected
- Env vars cannot be applied with restart, only with update source. Is it because of this or need a new bug? https://github.com/epinio/ui/issues/200

**Comment by richard-cox** [comment]
Sorry, functionality mix up.

For standard application env vars and custom values a restart of the application is required.

For the `EPINIO_APP_DATA` env var, it can be ignored. Storing them there is a byproduct of the create/edit process.

**Comment by mmartin24** [comment]
> Sorry, functionality mix up.
> 
> For standard application env vars and custom values a restart of the application is required.
> 
> For the `EPINIO_APP_DATA` env var, it can be ignored. Storing them there is a byproduct of the create/edit process.

Sorry, just to make sure I get it. So it is ok that on a deployed application, after an env var is added and saved, we need to click `Update Source`, correct?

**Comment by richard-cox** [comment]
The `Update Source` process is purely for updating the source of an application (there's some other stuff under the hood that changes env vars, but to the user these aren't a consideration). 

Updating env vars is done via the `Details` tab, the changes are persisted when `Save` is clicked and can be used by the app after it's been restarted.

**Comment by mmartin24** [comment]
Clarified offline.
The behavior of restate / rebuild will be checked separate for CLI.
Give this was only pending point, closing issue

**Comment by mmartin24** [comment]
> Clarified offline. The behavior of restate/rebuild will be checked separately for CLI. Given this was the only pending point, closing the issue

This has been tackled here: https://github.com/epinio/epinio/issues/2220

**Comment by mmartin24** [comment]
Retested in `v1.8.0-rc1` and working.
Done: Deployed Gitlab app, updated source to file, and updated source again to folder.
