### ISSUE TITLE
[UI] Epinio version for embedded mode 

### ISSUE THREAD

**Issue by scures** [epinio/ui#174]
As for the [fix](https://github.com/rancher/dashboard/pull/7559#discussion_r1037979517) of grabbing the Epinio version from the API, there's a need to adapt it once we move to the embedded plugin.

**Comment by richard-cox** [comment]
The standalone epinio ui uses `getVersionInfo` to fetch version info (which looks at the `server-version` setting resource). 
  - this is used to show the epinio version on the epinio home page and to construct links in the about page
  - Requested change - We use a new function that fetches from `await store.dispatch('epinio/request', { opt: { url: '/api/v1/info' } });`
  - Bonus points - We create a resource mock resource and schema, where this can be fetched and persisted from

In addition, slightly related so tagging on here
- excludes the `plugin/version` file (which makes a request `/rancherversion` to get a version, this would fail)
  - Requested change - We should mock this in the epinio ui backend to avoid excluding the `plugin/version` (which would be a pain to support in post-nuxt-removal world)

**Comment by torchiaf** [comment]
>  We create a resource mock resource and schema, where this can be fetched and persisted from

Do you mean using the store ?

**Comment by mmartin24** [comment]
Unsure exactly what to check. Mind please a small explanation / expected behavior here?
If the requirement is related to verifying the Epinio version displayed, pls mind the following comment [here](https://github.com/epinio/ui/issues/241#issuecomment-1576104330) as the links point to the main version and the version number displayed shows the full version including the commit.

**Comment by mmartin24** [comment]
Agreed offline this is similar to https://github.com/epinio/ui/issues/241#issuecomment-1576104330 already closed.
Closing issue ass well.
