### ISSUE TITLE
[UI]  Services bound to apps should not be allowed to be deleted until they are unbound.

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A service bound to an app can be deleted in UI without being unbound first.
![image](https://user-images.githubusercontent.com/37271841/207555138-2acb07e1-1fa2-4eea-8cce-c5663d20e5fa.png)

This behavior is different from CLI where unbinding is necessary prior service deletion as can be seen in this output:
```
➜  ~ epinio service bind svc-1 testapp       

🚢  Binding Service...
➜  ~ epinio service delete svc-1            

🚢  Deleting Services...
Names: svc-1
Namespace: workspace

⚠️  Unable to delete service. It is still used by
| BOUND APPLICATIONS |
|--------------------|
| testapp            |
⚠️  Use --unbind to force the issue
```

As extra information, when the same service is created again, it is automatically bound to the same application

### Expected Behavior

Service should be unbound from application automatically in the back prior its deletion
or
Service deletion should be prevented if bound to application and a warning message should be displayed advising the user to unbind it first.

### Steps To Reproduce

1. Install epinio UI
2. Create an app
3. Create a service (ie: mysql-dev)
4. Bind the service to app. Wait until is fully bound.
5. Delete the service with the app bound

### Environment

```markdown
- OS:Linux
- Architecture: amd64
- Epinio Version:1.5.1
- Cluster:
  - Provider: k3d
  - Options:
  - Kubernetes Version:v1.24.6
```

**Comment by richard-cox** [comment]
We should inform the user which apps the service is bound to and unbind them during the delete process.

From memory we have a similar pattern in Rancher Manager when deleting Roles that are bound to Principals.

Also need to consider what happens for configurations that have bindings and are deleted

**Comment by mmartin24** [comment]
Ok, I have tested further and the only case I can reproduce constantly is getting a 500 error when unbinding a service from an application:


```
xhr.js:178          PATCH https://epinio.192.168.16.3.omg.howdoi.website/pp/v1/direct/r/ZThhPrryoUeUuimbk4Gb-G3-I9A/api/v1/namespaces/workspace/applications/testapp-1 500
```
![Image](https://user-images.githubusercontent.com/37271841/229042496-500a7567-ffb3-4515-a576-aeb0bdee4a96.png)

@torchiaf , should we fix it here or want me to open a separate ticket?

**Comment by torchiaf** [comment]
> Ok, I have tested further and the only case I can reproduce constantly is getting a 500 error when unbinding a service from an application:
> 
> ```
> xhr.js:178          PATCH https://epinio.192.168.16.3.omg.howdoi.website/pp/v1/direct/r/ZThhPrryoUeUuimbk4Gb-G3-I9A/api/v1/namespaces/workspace/applications/testapp-1 500
> ```
> 
> ![Image](https://user-images.githubusercontent.com/37271841/229042496-500a7567-ffb3-4515-a576-aeb0bdee4a96.png)
> 
> @torchiaf , should we fix it here or want me to open a separate ticket?

I am not able to replicate the issue. Please open a separated issue.

**Comment by mmartin24** [comment]
> > Ok, I have tested further and the only case I can reproduce constantly is getting a 500 error when unbinding a service from an application:
> > ```
> > xhr.js:178          PATCH https://epinio.192.168.16.3.omg.howdoi.website/pp/v1/direct/r/ZThhPrryoUeUuimbk4Gb-G3-I9A/api/v1/namespaces/workspace/applications/testapp-1 500
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Image](https://user-images.githubusercontent.com/37271841/229042496-500a7567-ffb3-4515-a576-aeb0bdee4a96.png)
> > @torchiaf , should we fix it here or want me to open a separate ticket?
> 
> I am not able to replicate the issue, I guess it requires further investigations. Please open a separated issue.

@torchiaf . Agree. For some reason, this one and even other errors related to unbinding in configurations seem not consistent for me to reproduce. Opened https://github.com/epinio/epinio/issues/2183 to investigate.

Closing this issue

**Comment by mmartin24** [comment]
Rested in `v1.8.0-rc1`:
![image](https://user-images.githubusercontent.com/37271841/234634049-472f4c53-d50b-4612-be10-7e4203a1075b.png)
