### ISSUE TITLE
[UI] Appliction Shell breaks

### ISSUE THREAD

**Issue by scures** [epinio/ui#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking on `App Shell` button, it will break

![image](https://user-images.githubusercontent.com/88777903/218683148-50592481-0bad-494a-9955-10650eeba842.png)

### Expected Behavior

Should open a shell into the application container

### Steps To Reproduce

1. https://localhost:8005/epinio/c/default/applications
2. on any deployed app, click the 3 dots and click `App Shell`

### Environment

```markdown
- OS:
- Architecture:
- Epinio Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by mmartin24** [comment]
@scures, I am not sure I can reproduce.
I am able to open `App Shell` on a deployed app on latest `epinio-dev` with `v1.6.2-42-g1ed97378`

https://user-images.githubusercontent.com/37271841/218987982-0ab5a804-fe54-4180-8dad-4c66adea849b.mov

Am I missing perhaps any other step?

**Comment by richard-cox** [comment]
Agree, closing and we should monitor over the next week or so.
