### ISSUE TITLE
Feature Request: Allow to copy  logs in Epinio UI directly from screen

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#186]
### Is your feature request related to a problem?

Currently in Epinio UI, after deploying an app, if an user wants the logs he/she has to download them but can't copy directly from screen.

![image](https://user-images.githubusercontent.com/37271841/219292072-6880a080-8e09-4d67-b5d3-0de317b53580.png)

### Solution you'd like

As an internal user noticed the screen where logs appear should allow to copy the text.

**Comment by richard-cox** [comment]
This will be fixed when the next merge from dashboard master goes in to epinio-dev

**Comment by richard-cox** [comment]
Linking issue that will resolve it https://github.com/epinio/ui/issues/203

**Comment by mmartin24** [comment]
Checked on latest `epinio-dev` and working:

https://github.com/epinio/ui/assets/37271841/d4b15745-e4a4-46ec-966c-7db186cd47b4

Check also copying from in-built shell is possible:

https://github.com/epinio/ui/assets/37271841/76acc027-31e6-438e-855c-c754d0b877f7

**Comment by mmartin24** [comment]
Rechecked on `v1.9.0-rc3`
