### ISSUE TITLE
v1.5.0 → v1.6.0 when custom-build

### ISSUE THREAD

**Issue by scures** [epinio/ui#188]
### Solution you'd like

Changes the default version in the UI  to `v1.6.0` when we check custom builds

**Comment by richard-cox** [comment]
We need to review this with https://github.com/epinio/ui/issues/145#issuecomment-1446020913

**Comment by mmartin24** [comment]
If I understand correctly following the previous [comment](https://github.com/epinio/ui/issues/188#issuecomment-1446024296] the way to check is if by verifying the commit part is removed and just the current version is reachable. Should be the case I am still seeing the commit part present:

![image](https://user-images.githubusercontent.com/37271841/223094988-82948813-007f-48b0-8d74-d67e1da1bb9b.png)

@scures is this testable yet or still to be checked by dev team?
Maybe I may be missing somethinig?

**Comment by mmartin24** [comment]
Thanks @scures .
There it does thanks:
![image](https://user-images.githubusercontent.com/37271841/223110521-24432fe5-205d-4786-897f-ac515dbbc7cf.png)

**Comment by richard-cox** [comment]
In done column, closing
