### ISSUE TITLE
[UI] Redeploy from commit in App Detail view

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#197]
- App Detail page shows list of commits
- User should be able to select commit and via an action go to the new edit source wizard with the commit already selected
- To be done for github and gitlab after https://github.com/rancher/dashboard/pull/8334 merges

**Comment by mmartin24** [comment]
Tests done in latest `epinio-dev` and `Epinio Server Version: v1.9.0-rc2-28-ga496c920`

- Checked that re-deployment is possible for Github and Gitlab.
- Checked UI points to the requested commit when updating.
- Checked that the result changes according to the deployment commit (ie: in video, it changes from Packeto Buildpack static page to the Golang page)

https://github.com/epinio/ui/assets/37271841/9d435729-111d-4c12-b8d2-041797884eb0

**Comment by mmartin24** [comment]
Rechecked on `1.9.0-rc3` and working:
![image](https://github.com/epinio/ui/assets/37271841/30b1fb48-49f3-479d-995e-0e2701c0f945)

**Comment by mmartin24** [comment]
rechecked in 1.9.0
