### ISSUE TITLE
[UI] Missing GitLab Icon

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#198]
We need a GitLab icon to show in the Deployments details page.
Related Issues:

- https://github.com/rancher/dashboard/issues/8407
- https://github.com/epinio/ui/issues/173

**Comment by richard-cox** [comment]
Same, with this one, https://github.com/epinio/ui/issues/199?

**Comment by mmartin24** [comment]
@torchiaf / @richard-cox , would you please let us know the status of this one? Just wondering in grooming because it was tagged to 1.8.0. Thanks

**Comment by torchiaf** [comment]
> Just wondering in grooming because it was tagged to 1.8.0. Thanks

I think we can remove the milestone `1.8.0`, since it is a duplicate of this other one https://github.com/rancher/dashboard/issues/8407; anyway it is not urgent feature.

**Comment by torchiaf** [comment]
Done: https://github.com/rancher/icons/pull/62
