### ISSUE TITLE
[UI] Source type, wrong behavior when a Git type is selected

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#199]
Related issue: #173 

### Current Behavior
When switching from GitHub to GitLab (and viceversa), the repo name is not cleared.

### Expected Behavior
The repo name should be removed in the selection form

**Comment by richard-cox** [comment]
Isn't this part of https://github.com/epinio/ui/issues/173?

**Comment by torchiaf** [comment]
> Isn't this part of #173?

Yes, It's worth to resolve it in the same [PR](https://github.com/rancher/dashboard/pull/8354)
