### ISSUE TITLE
Feature Request: Add action to set the default application chart

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#201]
### Is your feature request related to a problem?

Adding ticket following comment [here](https://github.com/epinio/ui/issues/177#issuecomment-1473993832)

**Comment by richard-cox** [comment]
Opened on @richard-cox request, I need to update with details

**Comment by torchiaf** [comment]
Closing since the default chart is not handled at cluster level and cannot be changed from the UI at the moment.
