### ISSUE TITLE
[UI] Create Namespaces from Configurations and Applications is not possible after clicking cancel icon

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to create a namespace from Applications or Configurations page after clicking cancel (`X`) button on top right corner on Namespaces box is not possible

https://user-images.githubusercontent.com/37271841/228557483-7432fde7-e362-4b39-85a5-aa24c5f2e642.mov

### Expected Behavior

Creating a namespace should be still possible after clicking cancel

### Steps To Reproduce

1. Install Epinio UI
2. Click in `Configurations` menu
3. In the namespace box, click on `Create a New Namespace` (you can name now a namespace).
4. Click on the `X` that is displayed on top right corner of the namespace box
5. Click  again on `Create a New Namespace` and observe how it is not possible to create a new namespace.

### Environment

```markdown
- OS: Linux
- Architecture:amd64
- Epinio Version: v1.7.1-8-g9cf3ce3d
- Cluster:
  - Provider:k3d
  - Options:1 node
  - Kubernetes Version:v1.25.4+k3s1
```

**Comment by richard-cox** [comment]
Superseded by https://github.com/rancher/dashboard/pull/9112

**Comment by mmartin24** [comment]
@torchiaf I checked this on latest `epinio-dev` (`5858336219591cda57f486c2d6339c3f1fbe749a`) and I am still observing this issue.
I'm putting this back to `In progress`  to be re-checked, ok?
Thanks

**Comment by mmartin24** [comment]
ok, I rechecked this issue today with a new image and it seems working.
There is something strange because checking yesterday I used [this](https://github.com/epinio/ui-backend/actions/runs/5265592007/jobs/9518425917#step:13:835) image pointing to the commit pointed [above](https://github.com/epinio/ui/issues/205#issuecomment-1590927000). [Today's job](https://github.com/epinio/ui-backend/actions/runs/5274028807/jobs/9538080269#step:13:834) building the image points to the same commit so I am not sure what happened.

Anyhows checked the fix of this problem on configurations, applications and services and seems to work. 

https://github.com/epinio/ui/assets/37271841/7b8fe757-3213-480b-95e2-0649e5f8a9e3

Closing issue
