### ISSUE TITLE
[UI] Get a 500 error in creating new Configuration

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. Go to Advanced -> Configurations -> Create
2. Select an application to bind to the new Configuration (`Bind to Applications (optional)` option)
3. A 500 error is thrown:
```
details: "\nServer Backtrace: configuration not found"
status: 500
title: "configuration not found"
```

### Environment

```markdown
- OS:Linux
- Architecture: x64
- Epinio Version: latest
```

### Anything else?

![Epinio_configurations_500error](https://user-images.githubusercontent.com/26394656/229530076-56cbbbf9-6af3-4211-b99b-233a2c17b0c2.png)

**Comment by mmartin24** [comment]
@torchiaf , as commented offline I cannot reproduce this issue in steady manner. Maybe I am doing something wrong. 
Here is one example where I can create a config and bind it to app without issues:
![image](https://user-images.githubusercontent.com/37271841/229720730-53aac739-3baa-448e-919f-c3f31edd72ad.png)

And here another one where I triggered the error when adding a second app to bind to an existing one:
![image](https://user-images.githubusercontent.com/37271841/229721084-7ea66d52-cadc-4e2e-8f9a-14b9d1c9b76e.png)

However this inconsistent behavior seems familiar when I was checking these problems with binding / unbinding services [here](https://github.com/epinio/ui/issues/175#issuecomment-1490145488)
I am trying to investigate/narrow it down on this ticket: https://github.com/epinio/epinio/issues/2183

**Comment by torchiaf** [comment]
To test in updated environment: `v1.7.1`
