### ISSUE TITLE
[UI] Get a 500 error in creating new Service with Application bound

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A 500 error is thrown if we create a new Service and bound an Application for which a Configuration is defined.

Related issue: https://github.com/epinio/ui/issues/206

### Steps To Reproduce

0. Create a new Configuration `conf-1` and bind it to an Application `app-1`.
1. Go to Services -> Instances -> Create
2. Bind the application `app-1` to the new service, for which the Configuration `conf-1` is defined.

### Anything else?

![Epinio_500_service_create_with_config](https://user-images.githubusercontent.com/26394656/229535055-725986b4-3715-4af2-bb69-1424c5bed3a5.png)

**Comment by mmartin24** [comment]
@torchiaf 
I cannot reproduce this one either:
![image](https://user-images.githubusercontent.com/37271841/229722978-df1aefb0-8923-4fbb-aff6-9b12713b032c.png)

Trying to narrow it down on my side [here](https://github.com/epinio/epinio/issues/2183)

**Comment by torchiaf** [comment]
> @torchiaf I cannot reproduce this one either: ![image](https://user-images.githubusercontent.com/37271841/229722978-df1aefb0-8923-4fbb-aff6-9b12713b032c.png)
> 
> Trying to narrow it down on my side [here](https://github.com/epinio/epinio/issues/2183)

We will check if the issue is related to the testing environment.

**Comment by mmartin24** [comment]
> To test in updated environment: `v1.7.1`

@torchiaf, I retested in latest `epinio-dev` with latest epinio server version `v1.7.1-25-g96175d43` and I still cannot reproduce it.

![image](https://user-images.githubusercontent.com/37271841/231809288-6f4a2263-60b1-4480-87f7-55a7063cbc63.png)

Please let me know if you were able to reproduce or want to investigate anything else further; otherwise, I think we can close. I will move this one back to Epinio Icebox meanwhile.

**Comment by torchiaf** [comment]
> > To test in updated environment: `v1.7.1`
> 
> @torchiaf, I retested in latest `epinio-dev` with latest epinio server version `v1.7.1-25-g96175d43` and I still cannot reproduce it.
> 
> ![image](https://user-images.githubusercontent.com/37271841/231809288-6f4a2263-60b1-4480-87f7-55a7063cbc63.png)
> 
> Please let me know if you were able to reproduce or want to investigate anything else further; otherwise, I think we can close. I will move this one back to Epinio Icebox meanwhile.

Thanks @mmartin24 , it was a reminder for me mostly. I did some tests after we updated out dev environment and I can't  replicate the issue anymore. I think I'll close the ticket so far.

**Comment by torchiaf** [comment]
Cannot replicate in the new version.
