### ISSUE TITLE
[UI] Delete Services, applications count is wrong.

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user wants to delete a service, a warning message shows if there are zero or more applications bound to that services.
The count of bound applications in the warning message is wrong if there are more than 1 applications.

### Steps To Reproduce

- Create a Service, `svc-1`
- Bind the Service to 2 or more applications
- Select the service `svc-1` and click delete.
- The warning message is wrong, see the pic below

### Anything else?

![image](https://user-images.githubusercontent.com/26394656/229544508-5062aa70-6624-4c5f-ad66-7261efc31172.png)

**Comment by mmartin24** [comment]
Checked this issue in latest `epinio-dev` and seems working fine:

![image](https://user-images.githubusercontent.com/37271841/232726923-65ba62cb-347b-4249-a652-a297dab111b7.png)
