### ISSUE TITLE
[UI] Deploy Application Source - Selection Issues

### ISSUE THREAD

**Issue by scures** [epinio/ui#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

- When returning to the Source step the github commit is not re-selected
- gh valid state does not update to invalid if the user invalidates selection. For example select a gh username, repo, branc and commit, then change the username to something invalid and the next button is still enabled.

### Environment

```markdown
- OS:
- Architecture:
- Epinio Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by mmartin24** [comment]
Tested on latest `epinio-dev` and seems to work on update source.

1. It seems not working. 
Changing to a different repo and coming back to the original does not `remember` the initial commit selection. Please let me know if I tested this wrongly.

https://user-images.githubusercontent.com/37271841/233297699-3c7454fe-0885-46a0-8830-a766a2cf70e3.mov




2. Changing to a different/invalid repo disables the `Update source` seems to work
![image](https://user-images.githubusercontent.com/37271841/233295032-6c4d61a3-5cc8-4b2d-938d-fcd3b3849fc4.png)


However, I have a question. 
If I do the process of deploying an Application from scratch, selecting a commit, and then returning from the next screen. the selection is gone:

https://user-images.githubusercontent.com/37271841/233295490-58edcf09-589e-452b-b545-ab6c4cf03e3e.mov

Is this something for this ticket or should be spawned separately?

**Comment by richard-cox** [comment]
@mmartin24 

> 1. It seems not working.
>    Changing to a different repo and coming back to the original does not "remember" the initial commit selection. Please let me know if I tested this wrongly.

This is working as intended, once the user changes the repo they're resetting their git commit selection. We won't store repo <--> commit combinations mid-selection 

> 2. Changing to a different/invalid repo disables the `Update source` seems to work

> However, I have a question. If I do the process of deploying an Application from scratch, selecting a commit, and then returning from the next screen. the selection is gone:

> Is this something for this ticket or should be spawned separately?

That sounds like a bug, but it can be a separate ticket

**Comment by mmartin24** [comment]
> @mmartin24
> 
> > 1. It seems not working.
> >    Changing to a different repo and coming back to the original does not "remember" the initial commit selection. Please let me know if I tested this wrongly.
> 
> This is working as intended, once the user changes the repo they're resetting their git commit selection. We won't store repo <--> commit combinations mid-selection
> 

@richard-cox , ok then if misunderstood, could you pls specify what was the broken part on the [initial](https://github.com/epinio/ui/issues/209#issue-1655552816) issue in the description? Thanks
> When returning to the Source step the github commit is not re-selected

I will spin a ticket for the second one.

**Comment by richard-cox** [comment]
This has got a bit muddle, i thought this was the primary issue for updating source. I've updated the title to be more specific.

> When returning to the Source step the github commit is not re-selected

This means leaving the step and returning (next --> previous) the commit should be selected. From you second video it looks like this is still a bug. As it's listed in this original description no need for a second bug (sorry, my suggestion was based on the misunderstanding of the title)

> gh valid state does not update to invalid if the user invalidates selection. For example select a gh username, repo, branc and commit, then change the username to something invalid and the next button is still enabled.

From your first video this looks like it's working. The user is in an invalid state because no commit is selected after re-selecting the first branch.

I'll move this back on the stack as it hasn't been resolved

**Comment by richard-cox** [comment]
From my understanding there's only one issue left, and that's re-selecting the commit when returning to the page. 

Francesco has updated this process recently to support the removal of the app env var -
 https://github.com/rancher/dashboard/pull/8672. @torchiaf can you re-test this in your PR
