### ISSUE TITLE
[UI] App creation, error searching GitLab organization

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Searching a GitLab organization instead of User gives `404 error "User not found"`

### Expected Behavior

Searching a GitLab organization should returns the list of repositories

### Steps To Reproduce

1. Go To Applications
2. Create new app.
3. Selet GitLab type and search a GitLab org.

### Environment

```markdown
- OS:
- Architecture:
- Epinio Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by richard-cox** [comment]
closing, will be tested as part of https://github.com/epinio/ui/issues/173
