### ISSUE TITLE
[UI] Applications, fix number of commits for GitLab source

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- There is only one commit displayed
- The list of commits is displayed very slowly

### Environment

```markdown
- OS:
- Architecture:
- Epinio Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by richard-cox** [comment]
closing, will be tested as part of https://github.com/epinio/ui/issues/173
