### ISSUE TITLE
[UI] Application Source edit, wrong behavior when changing to Git source types

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

-a There is a case in which, if the application's source is GitHub and then it is changed to GitLab, the original source data is still displayed as current source.
-b In the same cases of point a, the 'Update Source' button remains active even if any commits/ repos/userOrOrg are selected.

### Expected Behavior

The original source data should be displayed only if the type is the same of that one from original source data, otherwise the form should be cleared.

### Steps To Reproduce

1. Select an existent `github` application and click on 'edit config' to change the application's source.
2. Switch the source type to 'Container'.
3. Switch again the source type to 'GitLab'.
4a. The source type is now `gitlab` but the form shows the original source data from `github`.
4b. The 'Update Source' is active.

### Screenshots
![epinio-app-source-bug](https://user-images.githubusercontent.com/26394656/232032445-644bed4f-957e-467e-b1c9-33a307969a37.gif)

**Comment by torchiaf** [comment]
Related PR: https://github.com/rancher/dashboard/pull/8672

**Comment by mmartin24** [comment]
Checked on latest epinio-dev and working

https://github.com/epinio/ui/assets/37271841/ecaf1b1a-9aeb-421d-9026-a59d58eac68b

**Comment by mmartin24** [comment]
verified in epinio `v1.8.1-rc1`
