### ISSUE TITLE
[UI] Disable configuration unbinding option for service rabbitmq

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Issue:
When an is bound to a `rabbitmq-dev` service, the user is allowed to unbind the `rabbitmq-config`part from configurations within the application/binding menu causing an error:

```
r.js:178     DELETE https://epinio.192.168.16.3.omg.howdoi.website/pp/v1/direct/r/ZThhPrryoUeUuimbk4Gb-G3-I9A/api/v1/namespaces/workspace/applications/testapp/configurationbindings/xd326256210974ceb2fde75b0d087-rabbitmq-config 400
```

https://user-images.githubusercontent.com/37271841/232086398-b0b2aa28-201e-403b-baa1-68d0dbaa30e1.mov

## Context
When creating the service `rabbitmq-dev` 2 bound configurations are created:

```
| Bound Configurations | xd326256210974ceb2fde75b0d087-rabbitmq,                                                                                 |
|                      | xd326256210974ceb2fde75b0d087-rabbitmq-config                                                                           |
```

When going to Applications > 3 dots > Bindings, we see how the `xd326256210974ceb2fde75b0d087-rabbitmq-config` part can be deselected from Configurations, causing the error. Per my understanding, this should be disabled.
![image](https://user-images.githubusercontent.com/37271841/232085218-81481223-83fe-4309-8da2-f003fcf93f17.png)

### Expected Behavior

Disable configuration unbinding possibility for service `rabbitmq-dev`

### Steps To Reproduce

1. Install Epinio & latest epnio ui
2. Push an app
3. Create service `rabbitmq-dev`
4. Bind it to the app
5. Go to App > 3 dots > Binding (Observe how `xd326256210974ceb2fde75b0d087-rabbitmq-config` is selectable)
6. Deselect `xd326256210974ceb2fde75b0d087-rabbitmq-config` + Click `Save` and observe the error.

### Environment

```markdown
- OS:Linux
- Architecture:amd64
- Epinio Version: v1.7.1-28-gf8057ed9
- Cluster:
  - Provider:k3d
  - Options:1 node
  - Kubernetes Version:v1.25.4
```

**Comment by enrichman** [comment]
We should check if the configuration coming from services have enough information to show where they are from.

They should have an `origin` field to understand that they are from a service, and those should not be visible.

**Comment by mmartin24** [comment]
I am still observing the same issue on the latest epiinio dev (`371dc4703c072e1039855177b21b63a492fc8180`)

![image](https://github.com/epinio/ui/assets/37271841/9f1d25ce-f64d-4d91-aaf3-fff8eac8a241)

**Comment by richard-cox** [comment]
Weird. Maybe we tested on our deployed instance with a 1.8.0 UI... which would suggest this is a regression. @torchiaf can you have a look?

**Comment by torchiaf** [comment]
> Weird. Maybe we tested on our deployed instance with a 1.8.0 UI... which would suggest this is a regression. @torchiaf can you have a look?

I'll take a look.

**Comment by torchiaf** [comment]
I confirm that is possible to edit bound configs from Application x -> Edit Config -> Bindings tab., so we can move this Issue to In Progress.
I did a test but the unbound action doesn't throw any errors.

**Comment by mmartin24** [comment]
Checked in latest `epinio-dev` and `Epinio Server Version: v1.9.0-rc2-1-g2240f783` and seems fixed. Now the UI does not offer the unbinding possibility.

![image](https://github.com/epinio/ui/assets/37271841/77d09371-95f3-45a2-9fc7-6a76b5361fdc)

**Comment by mmartin24** [comment]
rechecked in `1.9.0-rc3`:
![image](https://github.com/epinio/ui/assets/37271841/9d2bf0da-7355-4733-a2a0-e366825821dc)
