### ISSUE TITLE
Hide EPINIO_APP_DATA from user

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#220]

**Comment by mmartin24** [comment]
It would be nice to know if the expected behavior is to count env var once deployed.

**Comment by richard-cox** [comment]
@mmartin24 For the moment the only affected area will be editing env vars. Counts will remain unchanged

**Comment by mmartin24** [comment]
Checked the cosmetic change: the envar is not present any longer in the UI in details page, but counted as such.
![image](https://user-images.githubusercontent.com/37271841/232718661-969b115d-53a0-42f0-8515-c595d4b68c01.png)

Closing the issue waiting to discuss separately a possible better solution

**Comment by mmartin24** [comment]
Verified in `v1.8.0-rc1`
![image](https://user-images.githubusercontent.com/37271841/234632180-024d382a-725c-4dc2-b41f-85752991a6ab.png)
