### ISSUE TITLE
[ui] Feature Request: Add progress bar during export of Chart and Images

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#223]
### Is your feature request related to a problem?

Given that the export of a Chart and Images can be lengthy, we could add a progress bar for the user in the UI.

![image](https://user-images.githubusercontent.com/37271841/232463219-b23ca2a3-9e4c-4e80-ae05-0894e2b7486b.png)

**Comment by torchiaf** [comment]
> @torchiaf in theis repo we don't have the bot that automatically re-opens issues that were closed by merging a linked PR. this needs to happen manually. can you reopen this one and put it in to test?

Sure thing!

**Comment by thehejik** [comment]
[epinio.webm](https://github.com/epinio/ui/assets/12828077/2fa50d38-886a-4ec4-a0ec-06f271c01710)

Tested today with `ghcr.io/epinio/epinio-ui:latest-next` image. 

The progress bar is there but for some reason the last "Compressing Files" step (5:18) is not part of it and actually I believe the compression step itself started much earlier than announced. @torchiaf is that expected?

**Comment by torchiaf** [comment]
> epinio.webm 
> Tested today with `ghcr.io/epinio/epinio-ui:latest-next` image.
> 
> The progress bar is there but for some reason the last "Compressing Files" step (5:18) is not part of it and actually I believe the compression step itself started much earlier than announced. @torchiaf is that expected?

Hi @thehejik , this is not the same behavior we have in dev; the "Compressing files" label should be shown after ~1 second. Let me try it after refreshing our backend instance.

**Comment by torchiaf** [comment]
> epinio.webm 
> Tested today with `ghcr.io/epinio/epinio-ui:latest-next` image.
> 
> The progress bar is there but for some reason the last "Compressing Files" step (5:18) is not part of it and actually I believe the compression step itself started much earlier than announced. @torchiaf is that expected?

@thehejik the compression phase works as expected; there is an issue with progress bar calculation, I opened a new issue to fix it: #313 .
This will also include the compression phase as part of the progress bar.

**Comment by mmartin24** [comment]
> > epinio.webm
> > Tested today with `ghcr.io/epinio/epinio-ui:latest-next` image.
> > The progress bar is there but for some reason the last "Compressing Files" step (5:18) is not part of it and actually I believe the compression step itself started much earlier than announced. @torchiaf is that expected?
> 
> @thehejik the compression phase works as expected; there is an issue with progress bar calculation, I opened a new issue to fix it: #313 . This will also include the compression phase as part of the progress bar.

---
Hi @torchiaf, I will attempt to follow this issue as Tomas is on holiday this week.
So per my understanding, the current status on this particular ticket is that approximately 1-2 seconds after the progress bar is done, the compression phase, with the subsequent label should appear.  Nothing else correct? If this is so, it works as expected and I can close this, but I'd like to confirm with you first. 
Here I could see how approximately at second 20 the progress bar is done and the next part with the compression occurs

https://github.com/epinio/ui/assets/37271841/8eaf724e-1759-44be-87d9-329f12ada866

I understand that @thehejik comments are taken care of later on the next pr (313) where the compression is taken care altogether within the progress bar. Correct?

**Comment by torchiaf** [comment]
> > > epinio.webm
> > > Tested today with `ghcr.io/epinio/epinio-ui:latest-next` image.
> > > The progress bar is there but for some reason the last "Compressing Files" step (5:18) is not part of it and actually I believe the compression step itself started much earlier than announced. @torchiaf is that expected?
> > 
> > 
> > @thehejik the compression phase works as expected; there is an issue with progress bar calculation, I opened a new issue to fix it: #313 . This will also include the compression phase as part of the progress bar.
> 
> Hi @torchiaf, I will attempt to follow this issue as Tomas is on holiday this week. So per my understanding, the current status on this particular ticket is that approximately 1-2 seconds after the progress bar is done, the compression phase, with the subsequent label should appear. Nothing else correct? If this is so, it works as expected and I can close this, but I'd like to confirm with you first. Here I could see how approximately at second 20 the progress bar is done and the next part with the compression occurs
> 
>  Screencast.from.21-08-23.17.41.23.mov 
> I understand that @thehejik comments are taken care of later on the next pr (313) where the compression is taken care altogether within the progress bar. Correct?

Hi @mmartin24 correct. In addition, #313 will also fix a small an issue with the progress bar filling.
The issue is more visible in the video from Thomas (probably because the `image` is larger in his test).
With 313, the bar should gradually fills up.

**Comment by mmartin24** [comment]
> > > > epinio.webm
> > > > Tested today with `ghcr.io/epinio/epinio-ui:latest-next` image.
> > > > The progress bar is there but for some reason the last "Compressing Files" step (5:18) is not part of it and actually I believe the compression step itself started much earlier than announced. @torchiaf is that expected?
> > > 
> > > 
> > > @thehejik the compression phase works as expected; there is an issue with progress bar calculation, I opened a new issue to fix it: #313 . This will also include the compression phase as part of the progress bar.
> > 
> > 
> > Hi @torchiaf, I will attempt to follow this issue as Tomas is on holiday this week. So per my understanding, the current status on this particular ticket is that approximately 1-2 seconds after the progress bar is done, the compression phase, with the subsequent label should appear. Nothing else correct? If this is so, it works as expected and I can close this, but I'd like to confirm with you first. Here I could see how approximately at second 20 the progress bar is done and the next part with the compression occurs
> > Screencast.from.21-08-23.17.41.23.mov
> > I understand that @thehejik comments are taken care of later on the next pr (313) where the compression is taken care altogether within the progress bar. Correct?
> 
> Hi @mmartin24 correct. In addition, #313 will also fix a small an issue with the progress bar filling. The issue is more visible in the video from Thomas (probably because the `image` is larger in his test). With 313, the bar should gradually fills up.

Thanks @torchiaf for confirming.
Yes I saw the issue was clear on Tomas video taking longer times to appear the compression label. Mine simply shows the shorter time to appear the compression label. What I needed to know is if that was all the expected behavior for the moment. Since it seems to be, I will close the issue and later we can take a look at Tomas's comments on https://github.com/epinio/ui/pull/313

**Comment by thehejik** [comment]
Verified in `v1.10.0-rc1`
