### ISSUE TITLE
Feature Request: Remove the `EPINIO_APP_DATA` env variable

### ISSUE THREAD

**Issue by enrichman** [epinio/ui#228]
### Is your feature request related to a problem?

This variable is going to cause ~many~ some issues around, and we should try to remove it for the `v1.8.1`.

We should fetch all the needed information from the application manifest (ref: https://github.com/epinio/epinio/issues/2224)

### Solution you'd like
Info
- Application Source information will now come from the manifest (fetched in a separate API call, see https://github.com/epinio/ui/issues/227)
- App source info is used 
  - App Detail page
  - App Edit page

We need to 
- Remove places where the EPINIO_APP_DATA env var is managed
- Add to existing API requests the additional app source info
  - at the moment i think this is just git type and git branch where we sent the git url and git revision
- Add an async func to the app source
  - this fetches the manifest
  - parses manifest into the object we expect
- Call new app source func on app detail and edit pages

### Anything else?

Blocked on https://github.com/epinio/ui/issues/227

**Comment by mmartin24** [comment]
@torchiaf is this ready to test?
 I see it in our review column but I still see the app. 
 I tested against latest `epinio-dev`with commit `23d440198` already present (sso login labels)
 
 
![image](https://github.com/epinio/ui/assets/37271841/f65f17a2-3655-42f9-aeda-0244eaec5d1f)

**Comment by mmartin24** [comment]
@torchiaf  not sure if this is an item is not testable yet until https://github.com/rancher/dashboard/pull/8797 is merged.
I am moving this still to in progress on Epinio planning meanwhile is confirmed

**Comment by torchiaf** [comment]
> @torchiaf not sure if this item is not testable yet until [rancher/dashboard#8797](https://github.com/rancher/dashboard/pull/8797) is merged. I am moving this still to in progress on Epinio planning meanwhile is confirmed

Hi Martin, yes please, this one is not merged yet, (UI status is To Review).

**Comment by mmartin24** [comment]
It seems working in latest epinio-dev:

![image](https://github.com/epinio/ui/assets/37271841/95d8af54-47f8-4da0-aaee-9125a70e0440)

**Comment by mmartin24** [comment]
Verified in `1.8.1-rc1`:
![image](https://github.com/epinio/ui/assets/37271841/c2be9197-fd7b-415c-b347-acd75a990078)
