### ISSUE TITLE
[UI] Pushing Gitlab app broken at deployment stage

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#231]
## Issue
Deploying Gitlab app seems broken at deployment stage

![Image](https://user-images.githubusercontent.com/37271841/236162503-d73d1430-316b-44d8-8739-502b28d2341e.png)

Response error:
```json
{"errors":[{"status":400,"title":"json: cannot unmarshal object into Go struct field GitRef.origin.git.branch of type string","details":"failed to unmarshal deploy request"}]}
```

According to regression tests this seems to be occurring since 05/02/2023

## Steps to reproduce
- Deploy latest epinio 
- Deploy Gitlab app with the following config:
```
Username: richard-cox
Repository: epinio-sample-app
Branch: main
Commit: 07d2dd79 or bb688311
```

## Testing environment
Epinio Backend:
```
✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.25.4+k3s1
Epinio Server Version: v1.8.0-10-g123bdb6f
Epinio Client Version: v1.8.0-10-g123bdb6f
```

Epinio UI: 
Either latest in  epinio-dev or  
Image:          ghcr.io/epinio/epinio-ui:v1.8.0-0.0.1  

## Additional notes
When tested in the CLI, it seems to work ok. Pasting command to check (please observe full commit id is needed here):
```
epinio push --name testatpp-gitlab-cli-5 --git https://gitlab.com/richard-cox/epinio-sample-app,bb6883114668e9aed4964ed3f60bed3bc623c202
```

**Comment by andreas-kupries** [comment]
Note: looking at the json of the deploy request the json provides a `branch: { name: "thename" }` object.
The server expected a `branch: "thename"` string.

**Comment by mmartin24** [comment]
Working after fix above on latest `epinio-dev`:
![image](https://user-images.githubusercontent.com/37271841/236384389-bab4eebe-b9c3-415c-b2f1-10a712da3330.png)

UI test passing [here](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4889860099/jobs/8728756993#step:14:150)

**Comment by mmartin24** [comment]
Verified with automated tests [here](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5075980667/jobs/9117722713#step:14:145) and for `v1.8.1-rc1`
