### ISSUE TITLE
[ui] Sort github/gitlab repository and branch lists 

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#236]
- git component shows lists of repos and branches in drop downs
- lists should sort content alphabetically

**Comment by mmartin24** [comment]
Tests done in latest `epinio-dev` and `Epinio Server Version: v1.9.0-rc2-28-ga496c920`

Checked alphabetical order is enforced for repositories and branches. See attached screenshots as proof:

![image](https://github.com/epinio/ui/assets/37271841/ab762b77-88ac-4897-8c78-f8c4db947fd0) 
![image](https://github.com/epinio/ui/assets/37271841/943247ee-56cb-44b6-bede-e6a97e2d6c08)
![image](https://github.com/epinio/ui/assets/37271841/82bc544d-d46b-4618-abe9-175aca73c996)
