### ISSUE TITLE
[UI] The revision field is empty in `GitUrl` applications

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Screenshots

![image](https://github.com/epinio/ui/assets/26394656/cea1dceb-2982-427b-ba7b-eb837281c09b)

**Comment by mmartin24** [comment]
Tested on latest epinio-dev
Observed the revision here points to branch name 

![Image](https://github.com/epinio/ui/assets/37271841/fd54a6c6-973a-4cca-a63b-867b41fa3bc1)

as opposed to Gitlab where revision is a number and the branch name is separate:


![Image](https://github.com/epinio/ui/assets/37271841/86fc89ca-315f-485e-aaaa-b30bda177d2e)
@torchiaf explained to me this is expected current behavior although perhaps can be renamed in future tickets
