### ISSUE TITLE
[ui] Embedded - add link to about page

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#242]
Can be in the side menu (current standalone functionality) or somewhere on the epinio dashboard / home page

**Comment by thehejik** [comment]
@richard-cox could you please describe how to test and what is expected? I guess this is related to the extension and not to standalone ui, where I don't see any change.

**Comment by richard-cox** [comment]
Added issue to the global issue for testing embedded scenarios once close to production - https://github.com/epinio/ui/issues/265
