### ISSUE TITLE
[ui] Ensure CLI created git sourced applications manifests load correctly

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#245]
- See https://github.com/epinio/ui/issues/227#issuecomment-1573958190
- For apps created by the UI from github/gitlab there's a branch field
  - There's some work for the CLI to ensure the `branch` field is populated when it downlaods / creates a manifest
- For apps created by the CLI from git there's _probably_ no branch field
  - We need to confirm that when the UI loads a manifest from that app the source step shows the correct information
  - If it gets the type right (git) the branch / commit should be populated with the revision

**Comment by richard-cox** [comment]
Something isn't right there, we're showing `Gitlab` type instead of `Git`. There's probably still a bug, in that the branch is the revision, but worth fixing and re-testing

**Comment by mmartin24** [comment]
Tested on latest `epinio-dev`and `Epinio Server Version: v1.9.0-rc2-28-ga496c920`

Manifest created from CLI bringing `branch` field after fix here https://github.com/epinio/epinio/issues/2360 can be displayed in UI: 

![image](https://github.com/epinio/ui/assets/37271841/0d305c6d-c61b-4eaa-9fa9-1bc05e4698b1)

**Comment by mmartin24** [comment]
Rechecked in `v1.9.0-rc3`:
![image](https://github.com/epinio/ui/assets/37271841/dacfd9eb-5e35-4bdd-9f13-34eaa7baa98f)
