### ISSUE TITLE
Dex Role Mapping not working for Epinio UI

### ISSUE THREAD

**Issue by riqueps** [epinio/ui#246]
**Describe the bug**
After setup Dex OIDC connector and Role Mapping.
When a new user do first login on Epinio UI via Dex, the Dex role mapping is not being applied.

**To Reproduce**
Install epinio 1.8.0, setup [Dex oidc onnector and role mapping](https://epinio.gkestd.secureplatformcraftsmen.com/), to give Admin role on epinio, and do the first login on Epinio UI via Dex.
You gonna see that the user will receive `user` role.

**Expected behavior**
Apply the correct role mapping for EpinioUI too

**Login via EpinioUI**
Dex:
`time="2023-05-10T13:39:12Z" level=info msg="login successful: connector \"google\", username=\"Henrique Test\", preferred_username=\"\", email=\"henriquetest@domain.com\", groups=[\"group@domain.com\"]"`

K8s secret:
![image](https://github.com/epinio/epinio/assets/47371890/931f7d6c-f4f9-464f-a4db-462f3be03c24)

**Login via EpinioCLI**
Dex:
`time="2023-05-10T13:49:02Z" level=info msg="login successful: connector \"google\", username=\"Henrique Test\", preferred_username=\"\", email=\"henriquetest@domain.com\", groups=[\"group@domain.com\"]"`

K8s Secret:
![image](https://github.com/epinio/epinio/assets/47371890/6e0c5d61-08c5-4413-b7e5-dcce275a27a0)

Dex config file:
![image](https://github.com/epinio/epinio/assets/47371890/d2156cb3-e2eb-4cd7-86e8-7bcb0cc26bf5)

Role mapping config file:
![image](https://github.com/epinio/epinio/assets/47371890/5066ce4f-3a3f-42b5-9110-4378edb086c3)

**Comment by enrichman** [comment]
Opened a PR to fix this. It was due to a missing scope during the token exchange in the `ui-backend`.

The fix in now in review. :+1:
