### ISSUE TITLE
[UI] Export Application action doesn't work

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#250]
### Current Behavior

If User clicks on 'Export App' nothing happens. Related code seems to be this: https://github.com/rancher/dashboard/blob/1094f51b22f50089a07cc789f07779c529fc04fb/pkg/epinio/models/applications.js#L625

**Comment by mmartin24** [comment]
Automated tests passed again after this fix [here](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5353489551/jobs/9709428099#step:14:69). Note download max time there allowed is 5 mins to download the charts and images. This other issue was opened to see if this time can be revisited: https://github.com/epinio/ui/issues/254

Aside from this manual check on `v1.9.0-rc2-27-gbb562233` with latest `epinio-dev` in dashboard repo and passing. Showing small video for manifest immediate download and initiation of export for chart and images:

https://github.com/epinio/ui/assets/37271841/a90da812-614e-4cb4-a80a-bf5fd9a9d8c0
