### ISSUE TITLE
[UI] Export App creates a manifest-undefined on Epinio chart 1.8.1

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#251]
## Issue
While testing new Epinio chart for v1.8.1 it was noticed a `manifest.undefined` file when downloading a simple app folder
This was not observed initially when testing the functionality [here](https://github.com/epinio/ui/issues/170#issuecomment-1503421913)

![Image](https://user-images.githubusercontent.com/37271841/245481653-3617f5c9-6311-4d1d-97de-88f9a51f99ed.png)

## Steps to reproduce.

- Deploy Rancher v 2.7.5-rc5
- Install Epinio chart 1.8.1 (at the moment of the writing of the pr by using `git repo: https://github.com/epinio/charts.git branch epinio-1.8.1-integration`
- Go to the app and create a namespace
- Push folder application sample app: https://github.com/epinio/epinio/tree/main/assets/sample-app
- Download Chart and Images

## Observed behavior:
`manifest.undefined` file is created

**Comment by richard-cox** [comment]
@torchiaf Once https://github.com/epinio/ui/issues/250 is resolved can you check if this is reproducible in the latest code?

I don't think we'll need to do an emergency release to resolve this in the 1.8.x world

**Comment by torchiaf** [comment]
There is a dedicated tab to export the application manifest, so removing it from the zip file.

**Comment by thehejik** [comment]
Now the `Chart and Images` tab provides a zip archive without the `mainfest.undefined` file. Only expected files are present. Used `ghcr.io/epinio/epinio-ui:latest-next` built today.

![image](https://github.com/epinio/ui/assets/12828077/8f9b0a4e-47b9-4407-9a7a-034151dad861)

Also I was able to download only the `Manifest` by using the other tab. The manifest itself is named `workspace-sample-2023-06-20T15:14:09.yaml`  and contains relevant yaml data.

Thanks, closing as verified fixed.
