### ISSUE TITLE
[UI] Feature Request: page selection in Commits table of Git applications edit

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#253]
### Is your feature request related to a problem?

Given a commit, we need the possibility to programmaticaly select and show the page `x` where the commit is, in a table of `n` pages where the page `x` is not the first page of the table.
Related issue: https://github.com/epinio/ui/issues/197

**Comment by richard-cox** [comment]
@torchiaf  Once https://github.com/rancher/dashboard/pull/9179 merges we'll need a bump to shell before this issue moves to test

QA Note
- Deploy an application from a git hub / lab repo with a branch that contains a lot of commits
  - feel free to use GitLab `richard-cox/epinio-sample-app` and branch `lots-of-commits`
- Once deployed navigate to the Apps Detail page --> `Git commits` tab
- Select a commit to redeploy that appears on a page at least 1 away from the first one
- When the Edit App page is shown the selected commit should be visible in the `commits` table

**Comment by mmartin24** [comment]
Checked in `Epinio Server Version: v1.9.0-31-gb9618501` with latest Epinio UI.
Tested that by redeploying from several pages deep down a set of commits, the selection is now smart enough to take the user to the exact deployed commit.

This can be better viewed in the before / after comparison:

Before:

https://github.com/epinio/ui/assets/37271841/bebbf9f2-9188-4e31-882a-cfac3c48417a



After:

https://github.com/epinio/ui/assets/37271841/d40fa1bb-7835-4de2-a7c7-9db0254b14c8

**Comment by mmartin24** [comment]
Rechecked in `v1.10.0-rc1` and working.
