### ISSUE TITLE
[UI] Export of App over `Chart and Images` takes too long in comparison to CLI

### ISSUE THREAD

**Issue by thehejik** [epinio/ui#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Time for generating and offering an zip archive to download via `Chart and Images` tab when doing Export of existing app takes approx. 5 minutes. In comparison the same is doable over CLI within ~40 seconds. CLI just doesn't do the zip archive but generates the files (image, values.yaml, chart) directly.

### Expected Behavior

It is expected that the time will be similar in UI and CLI.

### Steps To Reproduce

1. Install Epinio, use latest UI image as `ghcr.io/epinio/epinio-ui:latest-next`
2. push an app (CLI or UI)
3. try to export `Chart and Images` over UI - it will take approx 5mins to offer the zip archive to download (downloading itself is fast then)
4. try the same over CLI `epinio app export sample .`

### Environment

```markdown
- OS:Linux
- Architecture: x86_64
- Epinio Version: v1.9.0-rc2-20-g2f2a5c95
- Cluster:
  - Provider: k3s
  - Options: single node
  - Kubernetes Version: v1.25.10+k3s1
```

**Comment by andreas-kupries** [comment]
Does the used zip package/library support adding files to an archive without compression?
Of the three files two are already compressed (image, chart tarball), so should be added without trying to compress them again.

**Comment by thehejik** [comment]
Verified in `v1.10.0-rc1`, now exporting a sample php app takes less than 2min.
