### ISSUE TITLE
[ui] Validate Epinio Extension when embedded in dashboard

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#265]
- Validate Epinio UI functionality when the extension is embedded in the dashboard
- ~This will be ready when https://github.com/epinio/ui/issues/192 is finished~ The MVP is nearly there, but enough is working that some testing is now appropriate
- We need to provide https://github.com/epinio/docs/issues/379
- We'll flesh this one out later but includes
 - CRUD of all resources
 - Authentication via local and dex users - https://github.com/epinio/ui/issues/129
 - Epinio 'About' page - https://github.com/epinio/ui/issues/242
   - https://github.com/epinio/ui/issues/309
 
Additions:
- Charts based on Kube metric server resources - https://github.com/epinio/ui/issues/270 (Pls see clarification needed [here](https://github.com/epinio/ui/issues/270#issuecomment-1695601366))
- Bug check: https://github.com/epinio/ui/issues/307 (Pls see clarification needed [here](https://github.com/epinio/ui/issues/307#issuecomment-1695611091))

**Comment by thehejik** [comment]
Validated on following setup:
Epinio version: v1.11.0-rc1 (+dev) installed over Rancher by using epinio/helm-charts repo and main branch
Epinio UI version: epinio-ui:v1.11.0-0.0.1 (+latest)
UI Extension: epinio-1.11.0-2
Rancher: v2.8.0-rc3 (+latest remote)
Browser type & version: vivaldi 6.4.3160.42

Testing focused on:
* CRUD of all resources OK (ns, app, service, config and binding/unbinding of service and config to existing app, changing routes, settings and ENV vars in existing apps)
* Context three dot menu for app and all entries verified
* App shells and logs visibility in Rancher environment
* Export of deployed application
* `Epinio App` context links present in Rancher's three dot menu for E apps (not for services) on Workload page
* Login and Auth by using Local User and Dex and also Log out from E in the extension
* About page - there is still `Rancher` string in many places

New issues opened:
* https://github.com/epinio/ui/issues/368 Export takes longer than in standalone ui
* https://github.com/epinio/ui/issues/309 About links with Rancher
* https://github.com/epinio/ui/issues/369 Scaling on app overview page (not extension related)
* https://github.com/epinio/ui/issues/371 Unable to confirm entered password for Local User by Enter in Extension 

Existing issues:
* https://github.com/epinio/ui/issues/322 Epinio must be installed in epinio namespace
* https://github.com/epinio/ui/issues/322 INVALID/CLOSED Log in info with Local User is not stored

Verified issues:
* https://github.com/epinio/ui/issues/270#issuecomment-1823053611 comment about metrics
* https://github.com/epinio/ui/issues/307#issuecomment-1823932046 comment about blank page from app detail

**Comment by thehejik** [comment]
Hope this can be closed.
