### ISSUE TITLE
[ui] add link from dashboard deployment to epinio app

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#271]
- link goes to embedded epinio app detail page
- need to confirm if there's a solid way to link kube deployment to epinio app

**Comment by richard-cox** [comment]
To also consider linking the native kube versions of configurations and services to their epinio counterparts

**Comment by thehejik** [comment]
Tested by deploying dev rancher `0fcff8c1` from epinio/ui/dashboard `main` branch.

The link `Epinio App` with E icon is present in three dots resource menu for Epinio `Deployments` and `Pods` in Rancher UI (local cluster). The link is not present for Epinio "Service" pods but this is expected.

![image](https://github.com/epinio/ui/assets/12828077/3b0df605-7547-479a-a759-4b1c18af1370)

**Comment by thehejik** [comment]
@richard-cox @torchiaf please does the report above cover everything? Can we close now?
