### ISSUE TITLE
[UI] - `min` property in metrics calculation is always zero

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#274]
![image](https://github.com/epinio/ui/assets/26394656/29899852-5b3c-4ff4-849c-5dbde39fd6a2)

**Comment by mmartin24** [comment]
Tested in latest `epinio-dev` with `Epinio Server Version: v1.9.0-5-gb075df24` deploying [example-12factor](https://github.com/epinio/example-12factor) with source type GitHub and noticed the difference

Before:
![2023-07-27_08-03](https://github.com/epinio/ui/assets/37271841/e10a8415-b2a2-4b46-84e3-504225a5f924)

After:
![2023-07-27_08-06](https://github.com/epinio/ui/assets/37271841/8f75dd58-643a-4044-8980-f468d2e2f30b)
