### ISSUE TITLE
[ui] Catalog Service is empty

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#296]
**Setup**
- Epinio UI version: 1.9.0

**To Reproduce**

Go To Services -> Edit a Service

**Screenshots**

![image](https://github.com/epinio/ui/assets/26394656/66ea7d28-fd3e-4724-b3dd-3b060b691468)

**Comment by mmartin24** [comment]
Verified in `Epinio Server Version: v1.9.0-23-g58d35b2e` with UI image `ghcr.io/epinio/epinio-ui:latest-next` and working.
Checked with mysql, postgres, rabbitmq, redis and mongo and ok.
Checked working with binded app and ok
Checked in Applications > bindings an ok (with several svcs bound)

![image](https://github.com/epinio/ui/assets/37271841/5e10a16c-b0eb-4b6f-a568-4d2c0582a2e9)

**Comment by mmartin24** [comment]
Rechecked in Epinio `v1.10.0-rc1`

![image](https://github.com/epinio/ui/assets/37271841/a661619e-2a8c-4b2a-938d-e3b44cfca801)
