### ISSUE TITLE
[ui] Custom Variables are not validated in Application edit mode

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#299]
**Setup**
- Epinio UI version: 1.9.0

**To Reproduce**

1- Edit an application having at least a custom variable with constraints (i.e. numeric variable with `min` value)
2- Set an invalid value. (i.e. min=5 value= 2)

**Result**
The Save button is enabled

**Expected Result**

Save button should be disabled.

**Screenshots**

![image](https://github.com/epinio/ui/assets/26394656/9c9297ec-bc10-4447-90d8-bb612d588ee0)

**Comment by thehejik** [comment]
Edit mode still not working, everything inactive so can't say if the values are validated but I can still press Save even if the form is inactive (the valid values entered when creating the service).

I guess some piece is still missing for the service Edit Mode enablement.
![image](https://github.com/epinio/ui/assets/12828077/e749f329-5fba-498d-a1d4-380501762cf5)

**Comment by thehejik** [comment]
Moving to `In Progress` until #252 is in.

**Comment by richard-cox** [comment]
@thehejik This issue is about application chart values, rather than service chart values. Would it be ok to create a validation issue for 1.11 for service chart values?

**Comment by richard-cox** [comment]
I've added a note to the edit service values issue to ensure values are validated https://github.com/epinio/ui/issues/252#issuecomment-1723040326.

**Comment by thehejik** [comment]
Edit still not possible, moving back to `In progress`.
![image](https://github.com/epinio/ui/assets/12828077/4e6409b0-9629-468c-8d5b-d170fb0bdb33)

**Comment by thehejik** [comment]
The validation works absolutely ok in chromium/vivaldi.

But doenst work at all in Firefox
![image](https://github.com/epinio/ui/assets/12828077/7cf84fe8-b743-4724-b1dd-068d63997885)

**Comment by thehejik** [comment]
This is from chromium/vivaldi, all the fields are validated and `Save` button is `Inactive` when even one value is out of range, also I was unable to write any letters into integer/number fields.

![image](https://github.com/epinio/ui/assets/12828077/6faae641-cc50-42d3-91a0-d474ba079820)

**Comment by thehejik** [comment]
Given the PR is merged and firefox issue opened I'm closing this one.

**Comment by mmartin24** [comment]
Verified in `v1.10.0-rc2` using Brave browser

- Negative values not allowed in `appListeningPort`
- Letters or special chars cannot be printed in screen in Chromium browsers. However this is possible in Firefox ones as mentioned in https://github.com/epinio/ui/issues/348
![image](https://github.com/epinio/ui/assets/37271841/838d0366-2c24-46bc-8fe8-4ff44f805242)
