### ISSUE TITLE
User can view logs from application

### ISSUE THREAD

**Issue by agracey** [epinio/ui#3]
This would include staging and running logs. It should also follow across builds so if I push again I shouldn't need to reload or click to a different application.

**Comment by richard-cox** [comment]
It looks like streaming Application / Staging Logs won't make it in to Beta2. It was proposed to handle auth in web sockets via cookie, however since we've now switched to contacting the Epinio API natively and not proxied these count as 'third-party' and there's a heap of issues with that

**Comment by catherineluse** [comment]
>  these count as 'third-party' and there's a heap of issues with that

Would it be feasible to have the Epinio server initiate the web socket for streaming logs? I'm thinking it won't violate CORS if the front end doesn't initiate it

**Comment by richard-cox** [comment]
Linking two issues blocking standalone ui 
- https://github.com/epinio/ui/issues/83
- https://github.com/epinio/ui/issues/84

One that's blocking embedded ui
- https://github.com/epinio/epinio/issues/1234

**Comment by richard-cox** [comment]
As per comment in https://github.com/epinio/ui/issues/83#issuecomment-1069229305, this has been fixed for both embedded and standalone and will be available in the next UI release after `0.6.0`
