### ISSUE TITLE
Export Applications modal, enhancements

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#301]
Related issues: #261

Export applications modal should be block, so if the user accidentally clicks outside of modal they don't lose the last x minutes of progress.

**Nice-to-have features**

Clicking cancel button / pressing Esc should cancel download.

**Comment by mmartin24** [comment]
Tested in `Epinio Server Version: v1.9.0-23-g58d35b2e` with latest ui image `ghcr.io/epinio/epinio-ui:latest-next `

- Checked pressing Esc / Cancel actually stops the export of images and charts
- Checked pressing outside the export window does not close the window and the download continues

The only thing to mention is that if Esc / Cancel is pressed when is compressing the files will not be stopped. Given that the compression will be part of the download on another ticket, I assume this as normal.

![image](https://github.com/epinio/ui/assets/37271841/3aca75d7-6f42-4be6-82f5-344a3e8aa34e)

**Comment by mmartin24** [comment]
Restested in Epinio `v1.10.0-rc1`
