### ISSUE TITLE
Navigating from an app detail page a cluster in cluster explorer throws white page error

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#307]
**To Reproduce**
- refresh on epinio app details page
- click on any cluster in the burger menu cluster list

**Result**
- white page error
```
console.js:31 TypeError: Cannot read properties of undefined (reading 'id')
    at EpinioApplicationModel.get (epinio-namespaced-resource.js:80:1)
    at VueComponent.namespaceLocation (Masthead.vue:148:1)
```

**Comment by mmartin24** [comment]
@richard-cox I am not sure about the context of this issue.
Please close it and add it to https://github.com/epinio/ui/issues/265
Thanks

**Comment by mmartin24** [comment]
@richard-cox, @torchiaf closing this issue and to be checked on #265 as suggested above. 

Again, I am not sure about the context of this error (do we need to have deployed Epinio using the extension, which one is the Epinio details page, 2 tabs are then opened?) so if you can provide them it would be great.

**Comment by torchiaf** [comment]
> @richard-cox, @torchiaf closing this issue and to be checked on #265 as suggested above.
> 
> Again, I am not sure about the context of this error (do we need to have deployed Epinio using the extension, which one is the Epinio details page, 2 tabs are then opened?) so if you can provide them it would be great.

@mmartin24 Correct, the error occurs when navigating from the Epinio UI - extension mode - to the Rancher explorer. You will have only 1 tab, since epinio is installed as an extension.

![epinio-extension](https://github.com/epinio/ui/assets/26394656/064d144a-1bd8-4bf2-b198-75e6e4de4e97)

**Comment by thehejik** [comment]
Retested on:
Epinio version: v1.11.0-rc1
Epinio UI version: epinio-ui:v1.11.0-0.0.1
UI Extension: epinio-1.11.0-2
Rancher: v2.8.0-rc3 (+latest remote)
Browser type & version: vivaldi 6.4.3160.42

Issue seems to be fixed, clicking on a cluster from app detail page is ok with dex and local user logged in and also refresh in app detail doesn't return error nor blank page.
