### ISSUE TITLE
[ui] Export applications, fix progress-bar behavior

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#312]
Related issue:  https://github.com/epinio/ui/issues/223#issuecomment-1682347773

- The progress bar fills up before the download is 100%.
- Add 'Compressing files' phase to the progress bar

**Comment by mmartin24** [comment]
Tested with `Epinio Server Version: v1.9.0-31-gb9618501` on the latest UI

- Checked that when the bar fills to 100%, it closes and the download is complete
- Checked that the compressing files part is now embedded

https://github.com/epinio/ui/assets/37271841/a12c4715-0151-4645-9d18-7e7e82ad8c34

**Comment by mmartin24** [comment]
Rechecked in `v1.10-0-rc2` and ok

**Comment by mmartin24** [comment]
Rechecked in `v1.10.0` and ok
