### ISSUE TITLE
[UI] 'Epinio' text is replaced by 'Rancher' after refreshing in 'About' page

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#315]
**Setup**
- Epinio version: `v1.9.0-21-g4b1a314b`
- Epinio UI version: 
```
│     Image:          ghcr.io/epinio/epinio-ui:latest-next                                                                                                                                       
│     Image ID:       ghcr.io/epinio/epinio-ui@sha256:c9c9c1e94d5d7b5f59a58eabbca09ac4c302588de6e602699155d791ccdd9755     
```
- Browser type & version: `Brave Version 1.57.47 Chromium: 116.0.5845.96 (Official Build)  (64-bit)`

**Describe the bug**
In about page links that contain the word 'Epinio' such as the binaries download links and links to Epinio repo are substituted by the text `Rancher` right after refreshing.

**To Reproduce**

- Deploy latest Epinio BE
- Deploy latest UI using `kubectl set image -n epinio deployment/epinio-ui epinio-ui=ghcr.io/epinio/epinio-ui:latest-next`
- Go to `About` page
- Observe text 'Epinio' on links to repo and binary downloads
- Refresh page

**Result**
`Epinio` text is substituted by `Rancher` one.

**Expected Result**
`Epinio` text is should remain

**Screenshots**

Before refresh:
![image](https://github.com/epinio/ui/assets/37271841/740a6539-8fa7-4dab-b82c-80ebd269bf2a)

After refresh:
![image](https://github.com/epinio/ui/assets/37271841/f8711f82-13a5-426c-9dc3-0be2a068f990)

Video:

https://github.com/epinio/ui/assets/37271841/bef7e7e0-5f9c-4253-a4f6-5318a2fbb2e7

**Additional context**

**Comment by richard-cox** [comment]
this will be a routing issue, and should be addressed the same time as https://github.com/epinio/ui/issues/309

**Comment by richard-cox** [comment]
In theory, this should be resolved as part of changes made in https://github.com/epinio/ui/pull/318.

**Comment by mmartin24** [comment]
Regression UI test 'Check "[About" page and main links](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6032923769/job/16368838133#step:14:143)' passed after fix.
Manually checked as well on `Epinio Server Version: v1.9.0-24-g3863a0d5
` and latest UI image `image: ghcr.io/epinio/epinio-ui:latest-next` after refreshing UI and working:

![image](https://github.com/epinio/ui/assets/37271841/8b76813e-bb15-46fa-846f-74827683734f)
