### ISSUE TITLE
[UI] Epinio UI deployed with dark theme when should be light

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#316]
**Setup**
- Epinio version: `v1.9.0-21-g4b1a314b`
- Epinio UI version: 
```
│     Image:          ghcr.io/epinio/epinio-ui:latest-next                                                                                                                                       
│     Image ID:       ghcr.io/epinio/epinio-ui@sha256:c9c9c1e94d5d7b5f59a58eabbca09ac4c302588de6e602699155d791ccdd9755     
```
- Browser type & version: `Brave Version 1.57.47 Chromium: 116.0.5845.96 (Official Build)  (64-bit)`

**Describe the bug**
Deploying latest Epinio with latest UI seems to display a dark theme once logged in in several browsers. However the ui-server pod shows it should be light:

**To Reproduce**

- Deploy latest Epinio BE. I use:
- On Epinio repo run:
```
git pull --recursive-submodules

make acceptance-cluster-delete && make acceptance-cluster-setup && export KUBECONFIG=$PWD/tmp/acceptance-kubeconfig && make install-cert-manager && make prepare_environment_k3d 
```
- Deploy latest UI using `kubectl set image -n epinio deployment/epinio-ui epinio-ui=ghcr.io/epinio/epinio-ui:latest-next`
- Open the UI on incognito to prevent possible skins set on default browser
- Observe login page with white skin, then log in.

**Result** 
Theme turns dark (Checked in Brave and Firefox)
![image](https://github.com/epinio/ui/assets/37271841/320f2606-3ab5-45a2-8bb7-ca5f495cb993)
- Now observe how the pod shows a light theme set on the `epinio-ui` pod 
```
 k describe deploy -n epinio epinio-ui | grep EPINIO_THEME 
      EPINIO_THEME:                 light
```

**Expected Result**

**Screenshots**

Video on Brave how it turns from light theme into dark:

https://github.com/epinio/ui/assets/37271841/941fb553-72d8-4a40-a8af-5330b27001f7

**Additional context**

**Comment by mmartin24** [comment]
Resuming here some of the things tried and commented on Slack.

- Tried deleting on my local, session and cookies via the Application tab (in particular the `R_PCS` which has `dark` value) and did not work.
- Tried changing OS values to light and did not work either
- Tried removing the browser theme.

The only thing that seems to have affected is changing in browser the default color to light (in Brave: settings > appearance > Brave colors > light). When this happens the cookie `R_PCS` turns to `light`. 

To me this is an unexpected behavior as it did not happen in earlier versions, it affects the user based on browser appearance, and it cannot be turned on as in Rancher or in Epinio docs with an icon. Not sure if the work done on the Epinio extension may have caused this.

**Comment by thehejik** [comment]
Same experience, only changing the browser appearance to `light` causes the post-v1.9.0  UI to be `light` again.

It seems that the theme settings are somehow inherited from the browser and cannot be changed by any setting in E UI nor by setting the `epinio-ui` deployment env var `EPINIO_THEME`.

**Comment by richard-cox** [comment]
From discussion, for 1.10 the UI should honour the theme as set via chart --> ui-backend.

Post 1.10 the UI needs to support preferences (https://github.com/epinio/ui/issues/128) to allow the user to disable the auto-detected theme

**Comment by richard-cox** [comment]
This is another one that's caused by the new upstream query param and fixed by changes in https://github.com/epinio/ui/pull/318. The failure to fetch user preferences was breaking the code later on to determine the light / dark mode.... so the UI was defaulting back to browser / OS

**Comment by mmartin24** [comment]
Tested on `Epinio Server Version: v1.9.0-24-g3863a0d5` and latest UI image `image: ghcr.io/epinio/epinio-ui:latest-next`.
I checked that now even when browser appearance settings are still dark (Cookie `R_PCS: dark`), the UI implements the light theme present in ui pod:   `EPINIO_THEME:  light`
![image](https://github.com/epinio/ui/assets/37271841/701dcaa6-d48d-4055-9344-88c652efd719)
Closing as fixed

**Comment by mmartin24** [comment]
Rested in `v1.10.0-rc1`

behavior of background controlled in pod deployment:

Dark:
![image](https://github.com/epinio/ui/assets/37271841/bb7492e4-276a-4387-a96c-019b69cc16c5)

Light:
![image](https://github.com/epinio/ui/assets/37271841/7843663c-95bd-4fae-b66e-872fc7ab2d14)
