### ISSUE TITLE
[UI] Service unbind broken in UI  

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#317]
**Setup**
- Epinio version: `v1.9.0-21-g4b1a314b`
- Epinio UI version: 
```
│     Image:          ghcr.io/epinio/epinio-ui:latest-next                                                                                                                                       
│     Image ID:       ghcr.io/epinio/epinio-ui@sha256:c9c9c1e94d5d7b5f59a58eabbca09ac4c302588de6e602699155d791ccdd9755     
```
- Browser type & version: `Brave Version 1.57.47 Chromium: 116.0.5845.96 (Official Build)  (64-bit)`

**Describe the bug**
Regression tests today found service unbind is broken in the UI.

**To Reproduce**
- Deploy the latest Epinio and UI
- Deploy an App
- Create as service `postgres-dev`
- Bind the service to the app (Note in dev tools > console, that the error appears, yet it will bind)
- Unbind 

**Result**
Unbind is not completed and the following error appears:

```
vue.runtime.esm.js:988 Uncaught (in promise) TypeError: Cannot set property details of [object Object] which has only a getter
```

**Expected Result**

**Screenshots**
![image](https://github.com/epinio/ui/assets/37271841/30970aec-3909-48c7-ab1c-6f13e72553a7)

Video:

https://github.com/epinio/ui/assets/37271841/0b3e741c-7748-4146-908d-a2b868ba39fd

**Additional context**

**Comment by torchiaf** [comment]
There is a new property in the returned object of http `/namespaces/${ns}/services/${svc}`:
```
{
  ...
  "details": {
      "mysql-password": "pass",
      "mysql-root-password": "root-pass"
  }
}
```
This field is not managed by service model in the UI.

@andreas-kupries @richard-cox  is this new property required in the response ? Are them sensible values ? I see the same values in the Service's Configuration page:

![image](https://github.com/epinio/ui/assets/26394656/cbb1c022-0902-42fe-86b1-4e01ff317a49)

@richard-cox do we have to handle this `details` value on the Epinio UI ? A workaround in the UI would be to put a `set` function

**Comment by andreas-kupries** [comment]
The field `details` is indeed new. See PR https://github.com/epinio/epinio/pull/2513 and ticket https://github.com/epinio/epinio/issues/2328

It provides information about the internals of a service, i.e. the available credentials keys and values from the configurations associated with the service.

This is not a thing to be set by the user. Treat it as read-only, do not write.

And apologies for not informing you (@richard-cox @torchiaf ) about this change.

**Comment by andreas-kupries** [comment]
Right now the `service listing` does not provide details, on account of the expense getting the data per service.

**Comment by mmartin24** [comment]
Regression UI tests related to service passing: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6032923769/job/16368838011#step:14:149

Manually checked as well on `Epinio Server Version: v1.9.0-24-g3863a0d5
` and latest UI image `image: ghcr.io/epinio/epinio-ui:latest-next`.

- Checked unbinding of 2 bound svc individually from the service screen
- Checked to unbind 3 services in bulk from Applicatios > bindings without errors
