### ISSUE TITLE
Show deployed commit in Application details/edit view

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#337]
**Is your feature request related to a problem? Please describe.**

Applications can be created by selecting a git repository/branch/commit as source.

For those applications, a Commits tab shows all commits in the selected branch and the commit the app was created from.
The commits tab is visible in both edit and details page of git applications and displays always the first page of the table.

If the repository contains a huge number of commits, It can happen that the source commit belongs to the second page.
As result, the commit source is not immediately visible to the user.

**Describe the solution you'd like**

Commits page should always display the table page where the commit source is.

**Screenshots**

First page
![image](https://github.com/epinio/ui/assets/26394656/d8b09da5-f529-4cf5-86bf-17a1042e8830)

Second page shows source commit
![Screenshot from 2023-09-05 09-46-42](https://github.com/epinio/ui/assets/26394656/e9b3567f-d53a-4f7c-bc36-7d2cac918ab3)

**Comment by richard-cox** [comment]
@torchiaf This has been completed in v1.10 right?
