### ISSUE TITLE
[ui] Supply service chart values when creating a service

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#338]
Add / Create side of https://github.com/epinio/ui/issues/252

**Comment by thehejik** [comment]
@richard-cox yes, agree, closing.

**Comment by thehejik** [comment]
Verified in `v1.10.0-rc2` - I could provide custom values defined in my custom service resource over UI, just the edit part in UI is missing (we know about that):
![image](https://github.com/epinio/ui/assets/12828077/8f14300c-2dfa-498c-bf5c-1cb56a3091c1)
