### ISSUE TITLE
[UI] Binding to an app broken if not done in 1 step

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#341]
**Setup**
- Epinio version: `v1.9.0-31-gb9618501`
- Epinio UI version: `ghcr.io/epinio/epinio-ui:latest-next`
- Browser type & version: `Brave Version 1.57.57 Chromium: 116.0.5845.163 (Official Build)  (64-bit)`

**Describe the bug**
It is not possible to bind a service to an app when the service is created first and attempted to bind secondly. (However, it does work when we try to do the binding in 1 single step)

**To Reproduce**

1. Create a fresh single-node cluster using latest Epinio server (`v1.9.0-31-gb9618501`, at the moment of this ticket) and patch latest Epinio UI using `kubectl set image -n epinio deployment/epinio-ui epinio-ui=ghcr.io/epinio/epinio-ui:latest-next`
2. Deploy an application (for instance: https://github.com/epinio/epinio/tree/main/assets/sample-app)
3. Deploy a service (ie postgresql-dev)
4. Go to service > instances and attempt to bind it to app

**Result**
Bind is not possible, displaying the error:

```
Service instance was created but failed to reach a deployed state in a reasonable amount of time, no applications were bound
```

https://github.com/epinio/ui/assets/37271841/21381610-b87e-4173-a02a-01d45d8b1476

**Expected Result**
Bind should happen

**Screenshots**

**Additional context**
As commented this does work if bound to app in 1 single step:

1. Create a fresh single-node cluster using latest Epinio server (`v1.9.0-31-gb9618501`, at the moment of this ticket) and patch latest Epinio UI using `kubectl set image -n epinio deployment/epinio-ui epinio-ui=ghcr.io/epinio/epinio-ui:latest-next`
2. Deploy an application (for instance: https://github.com/epinio/epinio/tree/main/assets/sample-app)
3. Go to service > instances and create a service (ie: `postgresql-dev`) and bind to the deployed app in 1 single step.

Result: app is correctly bound and no issues are shown

https://github.com/epinio/ui/assets/37271841/61a22573-812e-4550-b00d-21578f9bb892

**Comment by mmartin24** [comment]
Note: 
I am not sure if this issue should have been fixed after the merge of https://github.com/epinio/ui/pull/336 (already done) or if it may be fixed after the merge of https://github.com/epinio/ui/pull/340 (not done at the moment of this comment).

**Comment by richard-cox** [comment]
https://github.com/epinio/ui/issues/341 and https://github.com/epinio/ui/issues/342 will both be resolved by https://github.com/epinio/ui/pull/340

**Comment by mmartin24** [comment]
Checked after merge of https://github.com/epinio/ui/pull/340

It looks better but I see some hiccups. Check this one using  mongo db: It breaks
https://github.com/epinio/ui/assets/37271841/c1d1c914-03ab-4003-821c-49ee613f4110

I need to do more testing, but this at least happened.

**Comment by richard-cox** [comment]
@mmartin24 That's probably one for the core Epinio team. It looks like the `bind` request is made (see about 12 seconds in) and is stuck in pending. I'm guessing that times out after 2 minutes resulting in the failure.

**Comment by mmartin24** [comment]
Retested this issue this morning with Epinio Server Version `v1.9.0-32-g60affe85` and latest UI.

Checked the following for all these catalog services: `postgresql-dev`, `mongodb-dev`, `mysql-dev`, `rabbitmq-dev`, `redis-dev`
and could not find any issues, nor finding errors/warnings in the responses:

- Create services and bind them to an app in 1 step; unbind services 1 by 1 in the services tab.
- Create first, bind in the second step; unbind services 1 by 1 in the services tab.
- Create 2 services without waiting for others to be done, 5 seconds apart.
- Create, and bind 5 services to a single app, and unbind all services at once from the app tab.

Closing issue.

**Comment by mmartin24** [comment]
Retested in epinio `1.10.0-rc1` binding 1 by 1 with the 5 catalog services and working

**Comment by mmartin24** [comment]
Sanity check on `1.10.0` on postgresql-dev and working
