### ISSUE TITLE
[UI] Unbinding service an app not possible (possibly by service not-ready state)

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#342]
**Setup**

- Epinio version: `v1.9.0-31-gb9618501`
- Epinio UI version: `ghcr.io/epinio/epinio-ui:latest-next`
- Browser type & version: `Brave Version 1.57.57 Chromium: 116.0.5845.163 (Official Build)  (64-bit)`

**Describe the bug**

Unbinding is not possible again, but unlike in https://github.com/epinio/ui/issues/317 it does not seem broken. It throws a warning: `console.js:31 Error: Failed waiting for: service instance state = "not-ready"    at async.ts:14:16` and the unbinding is not happening. 
I am not sure if this may be fixed by https://github.com/epinio/ui/pull/340, but just writing up the issue just in case

**To Reproduce**

1. Create a fresh single-node cluster using latest Epinio server (`v1.9.0-31-gb9618501`, at the moment of this ticket) and patch latest Epinio UI using `kubectl set image -n epinio deployment/epinio-ui epinio-ui=ghcr.io/epinio/epinio-ui:latest-next`
2. Deploy an application (for instance: https://github.com/epinio/epinio/tree/main/assets/sample-app)
3. Go to service > instances and create a service (ie: `postgresql-dev`) and bind to the deployed app in 1 single step.
4. Wait until is bounded.
5. Attempt to unbind

**Result**
Not possible and the following message is displayed:
```
Service instance was created but failed to reach a deployed state in a reasonable amount of time, no applications were bound
```
https://github.com/epinio/ui/assets/37271841/0ddaeb31-b157-47c0-98b6-ef38bc570ff8

**Expected Result**
It should be possible

**Screenshots**

![image](https://github.com/epinio/ui/assets/37271841/129ec0d4-1285-45c8-9b73-a40d743dafcb)

**Additional context**

**Comment by richard-cox** [comment]
https://github.com/epinio/ui/issues/341 and https://github.com/epinio/ui/issues/342 will both be resolved by https://github.com/epinio/ui/pull/340

**Comment by mmartin24** [comment]
Tested in latest https://github.com/epinio/ui/pull/340 and overall seems to work, but I'd like to test more as I have had 1 error when unbinding, and not sure if it is a hiccup as in https://github.com/epinio/ui/issues/341#issuecomment-1708354749 or there is something else

**Comment by mmartin24** [comment]
Same as in https://github.com/epinio/ui/issues/341#issuecomment-1709550212

Retested this issue this morning with Epinio Server Version `v1.9.0-32-g60affe85` and the latest UI.

Checked the following for all these catalog services: `postgresql-dev`, `mongodb-dev`, `mysql-dev`, `rabbitmq-dev`, `redis-dev`
and could not find any issues, nor finding errors/warnings in the responses:

- Create services and bind them to an app in 1 step; unbind services 1 by 1 in the services tab.
- Create first, bind in the second step; unbind services 1 by 1 in the services tab.
- Create 2 services without waiting for others to be done, 5 seconds apart.
- Create, and bind 5 services to a single app, and unbind all services at once from the app tab.

Closing issue.

**Comment by mmartin24** [comment]
Rechecked in `epinio v1.10.0-rc1` and working.
Tested:
- Soft unbind 1 by 1 of different services
- Bulk unbinding of 5 services from applications

**Comment by mmartin24** [comment]
Rested in epinio v1.10.0-rc1.

Checked unbindings 1 by one
Checked bulk unbindings with 4 apps
