### ISSUE TITLE
[ui] With `Log in with Local User` the auth info is not stored in Rancher

### ISSUE THREAD

**Issue by thehejik** [epinio/ui#370]
**Setup**
- Epinio version: v1.11.0-rc1
- Epinio UI version: epinio-ui:v1.11.0-0.0.1
- UI Extension: epinio-1.11.0-2
- Rancher: v2.8.0-rc3
- Browser type & version: vivaldi 6.4.3160.42

**Describe the bug**
After login to Epinio via Rancher Extension and using `Local User` account user has to login over and over again on every attempt to go to Epinio via its `local` link in the extension.

But if Dex is used the auth info is kept and `Log Out` is shown (not the case for Local User).
![image](https://github.com/epinio/ui/assets/12828077/13e457d1-e9b8-454a-875d-800bd351d32c)

Also there is an Error if epinio app detail page is refreshed (not the case for Dex):
![image](https://github.com/epinio/ui/assets/12828077/4335ee2f-765c-4987-a2f9-3a1a9398449e)

**Comment by richard-cox** [comment]
There's two parts to this

- Persisting local user creds over reload - https://github.com/epinio/ui/issues/360
- Error page shown when user is not logged in - https://github.com/rancher/dashboard/pull/9941 (fixed in Rancher 2.8.next1

Closing as covered by linked issues
