### ISSUE TITLE
[ui] Permanent "Loading" first time installing Epinio Extension

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#377]
# Issue

When installing Epinio extension for the first time, I get a "loading" status permanently on the Epinio extension card. See the video below to better illustrate this

https://github.com/epinio/ui/assets/37271841/47e389ff-89a8-4adb-9df0-4e2a88eb7b0d

After refreshing it shows the correct status, but it does not happen until then.

Tested on Rancher `v2.8.0-rc3` 

# Steps to reproduce
- Fresh install on rancher `v2.8.0-rc3` 
- On Preferences, enable `Extension developer features` & `Include Prerelease Versions`
- Install Epinio extension as described in points 1 and 2 [here](https://github.com/epinio/ui/blob/main/docs/developer/README.md#production-flow)

**Comment by richard-cox** [comment]
@mmartin24  In the same environment can you reproduce the same behaviour with the KubeWarden extension?

**Comment by mmartin24** [comment]
> @mmartin24 In the same environment can you reproduce the same behaviour with the KubeWarden extension?

@richard-cox , I believe so. Pls check:

https://github.com/epinio/ui/assets/37271841/5d91596b-763e-404e-8c19-f07a9d9c31bb

**Comment by richard-cox** [comment]
@mmartin24 Thanks. This looks like a general issue with dashboard and extensions. I don't think i can transfer this over to `rancher/dashboard` though. Can you recreate the issue over at that repo?

**Comment by mmartin24** [comment]
> @mmartin24 Thanks. This looks like a general issue with dashboard and extensions. I don't think i can transfer this over to `rancher/dashboard` though. Can you recreate the issue over at that repo?

@richard-cox, done. Closing this issue in favor of https://github.com/rancher/dashboard/issues/10089
