### ISSUE TITLE
[ui] Epinio top right icon replaced by Rancher one

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#378]
# Issue:
When installing Epinio using the Rancher extension, the top right menu where Epinio would normally display the user is being replaced by the Rancher one. In the screenshot below we see the Rancher `admin` user whereas normally we would see the `epinio` user in this case (given that I logged in with this user)

![Image](https://github.com/epinio/ui/assets/37271841/9fdc12cc-9557-44f5-b4dc-09c6b445d932)

This is what normally we would see:

![Image](https://github.com/epinio/ui/assets/37271841/681905e4-5edd-4845-a683-5eb78710af8e)

Also this affects the logout process as instead of logging out from this user, it logs out completely from Rancher:

https://github.com/epinio/ui/assets/37271841/2180ade4-cbb5-443f-ad5e-776a34f03257

I would expect the behavior of this top right icon to be the same as in standalone, therefore I  will mark this initially as a bug, but feel free to resolve if this is intended by design.

Tested on fresh install on rancher `v2.8.0-rc3` using epinio `1.11.0-rc1`.

**Comment by richard-cox** [comment]
This is expected, the context of the user session is Rancher. 

We might need to think of a better way to show epinio user info, though that will be a different issue
