### ISSUE TITLE
Add warning about chain reaction when you delete a namespace

### ISSUE THREAD

**Issue by juadk** [epinio/ui#50]
When I delete a namespace where applications live, all the apps are deleted.
It's expected but we should warn the user before deleting.

![image](https://user-images.githubusercontent.com/6025636/142024944-7d05bb19-9620-413f-916d-099740350147.png)

I deployed `myfirstapp` in the namespace `mynamespace1`.

Then, I deleted the namespace mentioned above:
![image](https://user-images.githubusercontent.com/6025636/142025338-d5e5a9f3-18dc-4f5d-975b-dec40bfe5c5e.png)
![image](https://user-images.githubusercontent.com/6025636/142025434-baea235a-3c41-437b-940a-5ae9c7b99d16.png)

When the box disappeared, my application was also deleted without warning me about that chain reaction.

**Env**:
Rancher image: `rancher/rancher:v2.6.2`
Rancher dashboard branch: `epinio-v0.2.0-rc1`
Epinio: `0.1.6`
Rancher under docker connected to an external k3s cluster

After speaking with @richard-cox , it looks to be a regression.

**Comment by catherineluse** [comment]
The warning about the chain reaction was added here https://github.com/rancher/dashboard/pull/4447, but the PR was made to the `epinio-squashed` branch and it isn't currently in the `epinio-dev` branch.

**Comment by richard-cox** [comment]
@juadk The PR for this has merged and I've moved this issue to a new 'To Test' column in https://github.com/epinio/ui/projects/1. It's now available to test using the `ui-dashboard-index` value of `https://releases.rancher.com/dashboard/epinio-dev/index.html` (set as usual using the instructions at https://github.com/epinio/ui/tree/beta2). In terms of process does this work ok for you?

**Comment by juadk** [comment]
Yeah, perfect. I will test it for sure thanks.

**Comment by juadk** [comment]
Tested and fixed! thx
![image](https://user-images.githubusercontent.com/6025636/146209262-2d9738bd-f43c-49c8-a797-f29c04bfb45f.png)
