### ISSUE TITLE
Create application from git repo

### ISSUE THREAD

**Issue by agracey** [epinio/ui#54]
I'd like to create an app from a git through the UI in the same way I do with the archive and container image.

![image](https://user-images.githubusercontent.com/442274/143920550-2b7fabf5-456d-4102-9b14-52bbf2cfe7b6.png)

This is does not need to track git at the moment like my GitJob prototype does (although that would be nice)

**Comment by agracey** [comment]
@richard-cox I don't know what your backlog looks like but this would make demos much more appealing!

**Comment by richard-cox** [comment]
Completed by https://github.com/rancher/dashboard/commit/8f14788acb6182bde31050f97344648808eaae7f
