### ISSUE TITLE
List/Manage Application Instances

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#62]

**Comment by richard-cox** [comment]
https://github.com/epinio/epinio/issues/1118

**Comment by richard-cox** [comment]
@jimmykarily I've added a basic list showing application instances and their details. They have a single action (exec/shell). Is there any other current functionality or information we can show for instances?

![image](https://user-images.githubusercontent.com/18697775/158645951-c318602d-1efa-4773-8599-a1c2bafe5077.png)

**Comment by jimmykarily** [comment]
No that's it for now. It looks great!

**Comment by jimmykarily** [comment]
The port forwarding feature can target a specific instance too:

```
epinio app port-forward sample 8000:8000  -i sample-5445f9f5d9-wnn7m
```

**Comment by richard-cox** [comment]
@jimmykarily Given the browser environment i'm not sure how that action could be tied in, or is there additional info to show?

**Comment by jimmykarily** [comment]
True, let's skip. We could show a tip on how to forward ports but that would need us to maintain "documentation" in the front end. Let's not.
