### ISSUE TITLE
[UI Backend] Install Epinio UI using Helm

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#68]
- Repurpose existing stratos build process to create images
  - Bring in rancher dashboard ui files from rancher CND
  - Should images be renamed?
- Repurpose/Rebrand existing stratos helm chart to create an epinio ui chart
  - deployed pods, etc resource names should epinio-ui- (as opposed to stratos-)

**Comment by richard-cox** [comment]
After discussing with @nwmac , @jimmykarily and @manno it was decided for the 'alpha' standalone...
- A new chart will be created that will evetually be a subchart of epinio
- The chart will use a new epinio ui backend image
  - The image will contain
    - a jetstream binary (see epinio/ui-backend readme on how to create)
    - a version of the rancher/dashboard (fetched from https://releases.rancher.com/dashboard/<epinio dashboard version> - to confirm if these files can be cleanly fetched
  - The image will have a base image inline with other epinio images
- The chart will deploy the image and expose it as a service

The does not cover HA, in the future we'd need to bring back in the concept of DBs and persistent volumes

**Comment by jimmykarily** [comment]
Here is a first version of the helm chart: https://github.com/epinio/helm-charts/releases/tag/epinio-ui-0.0.1

Next step will be to make it a subchart of Epinio and allow the user to optionally install it alongside Epinio.

**Comment by jimmykarily** [comment]
Moved here: https://github.com/epinio/helm-charts/issues/110
