### ISSUE TITLE
[Standalone] Update dashboard favicon

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#76]
consider if this can be done at build time, otherwise code base would differ

**Comment by richard-cox** [comment]
This can be done with https://github.com/rancher/dashboard/pull/6080 and the ui-backend returning a built in favicon

**Comment by scures** [comment]
.ico & .png. I personally never use the .ico anymore

Result:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/88777903/173843244-a3b3a193-fa2f-4300-99ba-26bcb36f0e36.png">
[favicon.zip](https://github.com/epinio/ui/files/8909885/favicon.zip)
