### ISSUE TITLE
[UI Backend] Proxy Application and Staging Logs work

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#83]
TODO: Needs more info

**Comment by enrichman** [comment]
As discussed the problem was due to some strange issues between the Nuxt frontend proxy and the `ui-backend`. The only way we found to make it work was to actually build the frontend, and serving it through the backend:

```
OUTPUT_DIR=dist RANCHER_ENV=epinio yarn run build --spa
```

```
npm run build-backend

UI_PATH=<UI_PATH>/epinio/dashboard/dist \
    LOG_LEVEL=debug \
    EPINIO_API_WS_URL=wss://epinio.172.19.0.4.omg.howdoi.website \
    EPINIO_API_URL=https://epinio.172.19.0.4.omg.howdoi.website \
    EPINIO_API_SKIP_SSL=true \
    EPINIO_VERSION=v0.5.0-hmm \
    AUTH_ENDPOINT_TYPE=epinio \
    ./jetstream
```

**Comment by jimmykarily** [comment]
@richard-cox since we have a solution, will you integrate this in the UI to make Logs and exec work?

**Comment by richard-cox** [comment]
The frontend code has now been updated (in `rancher/dashboard` `epinio-dev`) and everything works fine when the UI is embedded into the dashboard and socket requests go straight to Epinio.

The backend code has has been updated (in `epinio/ui-backend` `main`) and works fine when not running in dev mode (see https://github.com/epinio/ui/issues/83#issuecomment-1060415306). In dev mode it still partially works but closes the connection after the opening set of messages (the connection is automatically reopened).

Both ui frontend and ui backend code changes are in the primary branches and will be in the ui release following 0.6.0. 

Note - https://github.com/epinio/ui/issues/84 is still an issue (fails to work)
