### ISSUE TITLE
[UI Backend] Proxy Application Instance Shell

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#84]

**Comment by richard-cox** [comment]
See comment in https://github.com/epinio/ui/issues/83#issuecomment-1069229305 for summary. TL;DR standalone ui can proxy logs when not in dev ok... however still cannot exec to an instance ok

**Comment by richard-cox** [comment]
I need to get together with someone Epinio backend side to work through this issue

**Comment by jimmykarily** [comment]
Maybe related: https://github.com/epinio/epinio/issues/1396

**Comment by richard-cox** [comment]
Following on from our call on the 11th

- https://github.com/epinio/ui-backend/tree/app-exec is the branch containing the backend changes (enabling client --> epinio messages)
- https://github.com/richard-cox/dashboard/tree/epinio-app-exec is the frontend branch with the tweaks to get app exec running as per the call. The commit message gives instructions on how to run it https://github.com/richard-cox/dashboard/commit/64b166189a135bf0a954eac7590b77261cbd041c

**Comment by richard-cox** [comment]
The frequent odd messages sent from client to proxy are terminal sizing info 


```
 const message = `4${ base64Encode(
        JSON.stringify({
          Width:  Math.floor(cols),
          Height: Math.floor(rows),
        })
      ) }`;

      this.socket.send(message);
```

**Comment by richard-cox** [comment]
Final note, same code works fine in the embedded/dashboard version of the epinio ui

**Comment by jimmykarily** [comment]
Refactored code to use the httputil ReverseProxy and fixed the cnsiURL to have a leading `/` in the `Path` (otherwise it doesn't work):

https://github.com/epinio/ui-backend/compare/v0.7.1-0.0.2...epinio:app-exec?expand=1

**Comment by jimmykarily** [comment]
Another small fix that broke logs for me: https://github.com/epinio/epinio/pull/1477/files
