### ISSUE TITLE
Restart application counter shouldn't print min / max / avg

### ISSUE THREAD

**Issue by juadk** [epinio/ui#87]
Spotted with epinio-ui:0.0.2 and epinio:0.5.0

From my point of view, it doesn't make sense to print `min / max / avg` counters for Restart. Only one counter is needed to know how many restart happened.

**Comment by richard-cox** [comment]
I've removed the stat, this changes will be available in the next UI release (after 0.6.0)

**Comment by juadk** [comment]
As the restart indicators were removed, let's close this issue.
![image](https://user-images.githubusercontent.com/6025636/165521209-b1dd27ea-20aa-4089-8769-842a3b568353.png)
