### ISSUE TITLE
Editing of Services

### ISSUE THREAD

**Issue by agracey** [epinio/ui#9]
A user should be able to edit their custom services

**Comment by richard-cox** [comment]
Blocked on https://github.com/epinio/epinio/issues/982

**Comment by richard-cox** [comment]
Blocked on https://github.com/epinio/epinio/issues/1104. There's changes needed due to something i missed in the review from previous changes

**Comment by richard-cox** [comment]
Editing a service is now enabled in `epinio-dev` and will be included in `0.3.3` (which will require epinio `v0.3.3`)
