### ISSUE TITLE
Last build logs button doesn't show up anything

### ISSUE THREAD

**Issue by juadk** [epinio/ui#93]
## Description:
In the UI, when you select an app, there is a button ‘Last Build logs’ but when I click on it. A new tab pops up but there is no log inside. I was expecting to see same logs I got when the app was building.

## Version used:
```
epinio: 0.8.1
ui-dashboard-index: epinio-v0.6.2
```

## Screenshot:
![image](https://user-images.githubusercontent.com/6025636/162991471-a1105aa1-a24e-4c8e-af23-96fc50ecba8f.png)

**Comment by richard-cox** [comment]
With latest `epinio/epinio` and using `/wapi/v1/namespaces/from-ui/staging/<app deployment.stage_id>/logs?follow=true&authtoken=...` I still see no staging logs. The socket is open and 'connected' but no messages are sent.

**Comment by jimmykarily** [comment]
This has something to do with how `follow: true` works: https://github.com/rancher/dashboard/blob/fdd90feecbd6cbe0876b1debba6d54aa73a73663/pkg/epinio/windowComponents/ApplicationLogs.vue#L138

When I set it to `false` I can see the logs of the last staging process. I'll investigate more.

**Comment by jimmykarily** [comment]
@richard-cox PR is merged, this is now fixed. Please re-open if you find otherwise.
