### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by enrichman** [epinio/ui#98]
### Is your feature request related to a problem?

When deleting a resource while holding `ctrl` there are no feedbacks about the deletion in progress.

### Solution you'd like

A small popup, alert, icon that will tell me that my action was received.

**Comment by richard-cox** [comment]
This is by design. If the modal that comes up without clicking ctrl doesn't contain the warning below please re-open with a wagging finger 

![image](https://user-images.githubusercontent.com/18697775/164765842-a4f7c636-9de9-44b2-975c-107ef7ecb29e.png)
